import { useMemo, useState, type FormEvent } from "react";
import { BookOpen, Copy, ExternalLink, File, FileText, FolderOpen, Link2, Pencil, Plus, Search, Trash2, Video, X } from "lucide-react";
import { LIMITS, subjectName, type AppData, type ResourceType, type StudyResource } from "../data";
import { inferResourceType, normalizeResourceUrl, resourceHost } from "../resourceUtils";

type Props = { data: AppData; mutate: (updater: (data: AppData) => AppData) => void; fixedSubjectId?: string; embedded?: boolean };
const types: Array<{ id: ResourceType | "all"; label: string }> = [{ id: "all", label: "Todos" }, { id: "link", label: "Links" }, { id: "video", label: "Vídeos" }, { id: "pdf", label: "PDFs" }, { id: "article", label: "Artigos" }, { id: "document", label: "Documentos" }, { id: "folder", label: "Pastas" }, { id: "other", label: "Outros" }];
const labels: Record<ResourceType, string> = { link: "Link", video: "Vídeo", pdf: "PDF", article: "Artigo", document: "Documento", folder: "Pasta", other: "Outro" };
const icons = { link: Link2, video: Video, pdf: FileText, article: BookOpen, document: File, folder: FolderOpen, other: File };

function Biblioteca({ data, mutate, fixedSubjectId, embedded = false }: Props) {
  const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<StudyResource>(); const [search, setSearch] = useState(""); const [type, setType] = useState<ResourceType | "all">("all"); const [subjectFilter, setSubjectFilter] = useState(""); const [collection, setCollection] = useState(""); const [error, setError] = useState("");
  const collections = useMemo(() => [...new Set(data.resources.filter((item) => !fixedSubjectId || item.subjectId === fixedSubjectId).map((item) => item.collection).filter(Boolean))].sort((a, b) => a.localeCompare(b, "pt-BR")), [data.resources, fixedSubjectId]);
  const resources = useMemo(() => data.resources.filter((item) => {
    const matchesSubject = !subjectFilter || (subjectFilter === "general" ? !item.subjectId : item.subjectId === subjectFilter);
    const searchable = `${item.title} ${item.description} ${item.tags.join(" ")} ${resourceHost(item.url)}`.toLocaleLowerCase("pt-BR");
    return (!fixedSubjectId || item.subjectId === fixedSubjectId) && matchesSubject && (type === "all" || item.type === type) && (!collection || item.collection === collection) && (!search.trim() || searchable.includes(search.trim().toLocaleLowerCase("pt-BR")));
  }).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)), [collection, data.resources, fixedSubjectId, search, subjectFilter, type]);
  const closeForm = () => { setEditing(undefined); setShowForm(false); setError(""); };
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError("");
    try {
      const form = new FormData(event.currentTarget); const subjectId = fixedSubjectId ?? (String(form.get("subjectId") || "") || undefined);
      if (!editing && (data.resources.length >= LIMITS.resources || subjectId && data.resources.filter((item) => item.subjectId === subjectId).length >= LIMITS.resourcesPerSubject)) return setError("O limite de materiais deste espaço foi atingido.");
      const url = normalizeResourceUrl(String(form.get("url") || "")); const selectedType = String(form.get("type") || "auto"); const now = new Date().toISOString();
      const resource: StudyResource = { id: editing?.id ?? crypto.randomUUID(), subjectId, title: String(form.get("title") || "").trim().slice(0, LIMITS.title), url: url.slice(0, LIMITS.resourceUrl), type: selectedType === "auto" ? inferResourceType(url) : selectedType as ResourceType, description: String(form.get("description") || "").trim().slice(0, LIMITS.resourceDescription), tags: String(form.get("tags") || "").split(",").map((tag) => tag.trim()).filter(Boolean).slice(0, 12), collection: String(form.get("collection") || "").trim().slice(0, 80), createdAt: editing?.createdAt ?? now, updatedAt: now };
      mutate((current) => ({ ...current, resources: editing ? current.resources.map((item) => item.id === editing.id ? resource : item) : [resource, ...current.resources] })); closeForm();
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível salvar este material."); }
  };
  const remove = (item: StudyResource) => window.confirm(`Excluir “${item.title}” da Biblioteca?`) && mutate((current) => ({ ...current, resources: current.resources.filter((entry) => entry.id !== item.id) }));

  return <div className={embedded ? "library embedded-library" : "page library library-page"}>
    <section className="page-toolbar"><div><span className="eyebrow">REFERÊNCIAS DE ESTUDO</span><p className="muted">Salve o caminho para seus materiais sem armazenar os arquivos no OmniDesk.</p></div><button className="primary-button" onClick={() => showForm ? closeForm() : setShowForm(true)}>{showForm ? <X size={18} /> : <Plus size={18} />}{showForm ? "Cancelar" : "Novo material"}</button></section>
    {showForm && <form key={editing?.id ?? "new"} className="panel resource-form" onSubmit={submit}><label>Título<input name="title" defaultValue={editing?.title} maxLength={LIMITS.title} placeholder="Ex.: Playlist de Direito Administrativo" required autoFocus /></label><label className="resource-url-field">Endereço<input name="url" type="text" inputMode="url" defaultValue={editing?.url} maxLength={LIMITS.resourceUrl} placeholder="youtube.com/... ou https://..." required /><small>Links recebem tratamento especial e abrem sempre em uma nova aba.</small></label><label>Tipo<select name="type" defaultValue={editing?.type ?? "auto"}><option value="auto">Detectar automaticamente</option>{types.slice(1).map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label>{!fixedSubjectId && <label>Matéria <span className="optional">opcional</span><select name="subjectId" defaultValue={editing?.subjectId ?? ""}><option value="">Geral / sem matéria</option>{data.subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.title}</option>)}</select></label>}<label>Coleção <span className="optional">opcional</span><input name="collection" defaultValue={editing?.collection} list="resource-collections" placeholder="Ex.: PDFs do edital" maxLength={80} /><datalist id="resource-collections">{collections.map((item) => <option value={item} key={item} />)}</datalist></label><label>Tags <span className="optional">opcional</span><input name="tags" defaultValue={editing?.tags.join(", ")} placeholder="revisão, prova, prioridade" /></label><label className="resource-description">Descrição <span className="optional">opcional</span><textarea name="description" defaultValue={editing?.description} maxLength={LIMITS.resourceDescription} placeholder="Anote por que este material é útil." /></label>{error && <p className="resource-error" role="alert">{error}</p>}<button className="primary-button">{editing ? "Salvar alterações" : "Adicionar à Biblioteca"}</button></form>}
    <section className="library-filters"><label className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar por título, site ou tag" /></label><select value={type} onChange={(event) => setType(event.target.value as ResourceType | "all")} aria-label="Filtrar por tipo">{types.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select>{!fixedSubjectId && <select value={subjectFilter} onChange={(event) => setSubjectFilter(event.target.value)} aria-label="Filtrar por matéria"><option value="">Todas as matérias</option><option value="general">Somente gerais</option>{data.subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.title}</option>)}</select>}<select value={collection} onChange={(event) => setCollection(event.target.value)} aria-label="Filtrar por coleção"><option value="">Todas as coleções</option>{collections.map((item) => <option value={item} key={item}>{item}</option>)}</select></section>
    <section className="resource-grid">{resources.map((item) => { const Icon = icons[item.type]; return <article className="panel resource-card" key={item.id}><div className={`resource-icon resource-${item.type}`}><Icon /></div><div className="resource-main"><span><i>{labels[item.type]}</i>{item.collection && <i>{item.collection}</i>}</span><h3>{item.title}</h3><a href={item.url} target="_blank" rel="noopener noreferrer">{resourceHost(item.url)} <ExternalLink size={13} /></a>{item.description && <p>{item.description}</p>}<div className="resource-meta"><small>{subjectName(data, item.subjectId)}</small>{item.tags.map((tag) => <small key={tag}>#{tag}</small>)}</div></div><div className="resource-actions"><button onClick={() => void navigator.clipboard?.writeText(item.url)} title="Copiar endereço" aria-label={`Copiar endereço de ${item.title}`}><Copy /></button><button onClick={() => { setEditing(item); setShowForm(true); window.scrollTo({ top: 0, behavior: "smooth" }); }} title="Editar" aria-label={`Editar ${item.title}`}><Pencil /></button><button className="danger" onClick={() => remove(item)} title="Excluir" aria-label={`Excluir ${item.title}`}><Trash2 /></button></div></article>; })}{!resources.length && <div className="empty-state panel empty-wide"><BookOpen /><h3>Nenhum material encontrado</h3><p>Salve vídeos, PDFs, artigos e outros links úteis para acessá-los rapidamente.</p></div>}</section>
  </div>;
}

export default Biblioteca;
