import { CalendarClock, ChevronLeft, ChevronRight, Clock3, Copy, Edit3, Plus, Sparkles, Trash2, X } from "lucide-react";
import { useMemo, useState } from "react";
import { LIMITS, subjectName, type AppData, type ScheduleCategory, type ScheduleEntry } from "../data";

const DAYS = ["Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Domingo"];
const CATEGORIES: { id: ScheduleCategory; label: string }[] = [{ id: "study", label: "Estudo" }, { id: "review", label: "Revisão" }, { id: "assignment", label: "Trabalho" }, { id: "break", label: "Pausa" }, { id: "personal", label: "Pessoal" }, { id: "other", label: "Outro" }];
const minutes = (value: string) => { const [h, m] = value.split(":").map(Number); return h * 60 + m; };
const todayIndex = () => (new Date().getDay() + 6) % 7;
type Draft = { title: string; description: string; startTime: string; endTime: string; category: ScheduleCategory; subjectId: string; days: number[] };
const freshDraft = (day = todayIndex()): Draft => ({ title: "", description: "", startTime: "14:00", endTime: "15:00", category: "study", subjectId: "", days: [day] });

function Cronograma({ data, mutate }: { data: AppData; mutate: (updater: (data: AppData) => AppData) => void }) {
  const [selectedDay, setSelectedDay] = useState(todayIndex()); const [editing, setEditing] = useState<string>(); const [draft, setDraft] = useState<Draft>();
  const ordered = useMemo(() => [...data.scheduleEntries].sort((a, b) => a.day - b.day || a.startTime.localeCompare(b.startTime)), [data.scheduleEntries]);
  const now = new Date(); const nowMinutes = now.getHours() * 60 + now.getMinutes(); const today = todayIndex();
  const current = ordered.find((item) => item.day === today && minutes(item.startTime) <= nowMinutes && minutes(item.endTime) > nowMinutes);
  const next = ordered.find((item) => item.day === today && minutes(item.startTime) > nowMinutes) ?? ordered.find((item) => item.day > today) ?? ordered[0];
  const openNew = (day = selectedDay, startTime?: string) => { const value = freshDraft(day); if (startTime) { value.startTime = startTime; value.endTime = `${String(Math.min(23, Number(startTime.slice(0, 2)) + 1)).padStart(2, "0")}:${startTime.slice(3)}`; } setEditing(undefined); setDraft(value); };
  const openEdit = (entry: ScheduleEntry) => { setEditing(entry.id); setDraft({ title: entry.title, description: entry.description, startTime: entry.startTime, endTime: entry.endTime, category: entry.category, subjectId: entry.subjectId ?? "", days: [entry.day] }); };
  const save = () => {
    if (!draft || !draft.title.trim()) return; if (minutes(draft.endTime) - minutes(draft.startTime) < 5) return window.alert("O bloco precisa ter ao menos 5 minutos.");
    const conflicts = data.scheduleEntries.some((entry) => entry.id !== editing && draft.days.includes(entry.day) && minutes(draft.startTime) < minutes(entry.endTime) && minutes(draft.endTime) > minutes(entry.startTime));
    if (conflicts && !window.confirm("Este horário se sobrepõe a outro bloco. Deseja salvar mesmo assim?")) return;
    const nowIso = new Date().toISOString(); mutate((currentData) => { if (editing) return { ...currentData, scheduleEntries: currentData.scheduleEntries.map((entry) => entry.id === editing ? { ...entry, title: draft.title.trim().slice(0, LIMITS.scheduleTitle), description: draft.description.trim().slice(0, LIMITS.scheduleDescription), startTime: draft.startTime, endTime: draft.endTime, category: draft.category, subjectId: draft.subjectId || undefined, day: draft.days[0], updatedAt: nowIso } : entry) }; const room = LIMITS.scheduleEntries - currentData.scheduleEntries.length; const entries = draft.days.slice(0, room).map((day) => ({ id: crypto.randomUUID(), title: draft.title.trim().slice(0, LIMITS.scheduleTitle), description: draft.description.trim().slice(0, LIMITS.scheduleDescription), startTime: draft.startTime, endTime: draft.endTime, category: draft.category, subjectId: draft.subjectId || undefined, day, createdAt: nowIso, updatedAt: nowIso })); return { ...currentData, scheduleEntries: [...currentData.scheduleEntries, ...entries] }; }); setDraft(undefined); setEditing(undefined);
  };
  const remove = (id: string) => { if (window.confirm("Excluir este bloco do cronograma?")) mutate((currentData) => ({ ...currentData, scheduleEntries: currentData.scheduleEntries.filter((entry) => entry.id !== id) })); };
  const duplicate = (entry: ScheduleEntry) => { if (data.scheduleEntries.length >= LIMITS.scheduleEntries) return; const nextDay = (entry.day + 1) % 7; mutate((currentData) => ({ ...currentData, scheduleEntries: [...currentData.scheduleEntries, { ...entry, id: crypto.randomUUID(), day: nextDay, title: `${entry.title} (cópia)`, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }] })); };
  const clearDay = () => { if (!window.confirm(`Limpar todos os blocos de ${DAYS[selectedDay]}?`)) return; if (!window.confirm("Esta ação não pode ser desfeita. Confirma a exclusão?")) return; mutate((currentData) => ({ ...currentData, scheduleEntries: currentData.scheduleEntries.filter((entry) => entry.day !== selectedDay) })); };
  const copyDay = () => { const source = data.scheduleEntries.filter((entry) => entry.day === selectedDay); if (!source.length) return; const target = (selectedDay + 1) % 7; if (!window.confirm(`Copiar os ${source.length} blocos de ${DAYS[selectedDay]} para ${DAYS[target]}?`)) return; mutate((currentData) => { const room = LIMITS.scheduleEntries - currentData.scheduleEntries.length; const stamp = new Date().toISOString(); return { ...currentData, scheduleEntries: [...currentData.scheduleEntries, ...source.slice(0, room).map((entry) => ({ ...entry, id: crypto.randomUUID(), day: target, createdAt: stamp, updatedAt: stamp }))] }; }); };
  const clearWeek = () => { if (!data.scheduleEntries.length || !window.confirm("Limpar todo o cronograma semanal?")) return; if (!window.confirm("Todos os blocos serão excluídos. Confirma definitivamente?")) return; mutate((currentData) => ({ ...currentData, scheduleEntries: [] })); };
  const dayEntries = ordered.filter((item) => item.day === selectedDay);
  return <main className="page schedule-page">
    <section className="schedule-hero"><div><span className="eyebrow">PLANO DA SEMANA</span><h2>Sua rotina, com espaço para respirar.</h2><p>Organize estudos, revisões, entregas e pausas sem transformar o dia numa lista infinita.</p></div><div className="schedule-now"><Sparkles /><span>{current ? "Acontecendo agora" : "Próximo compromisso"}</span><strong>{(current ?? next)?.title ?? "Semana livre"}</strong>{(current ?? next) && <small>{DAYS[(current ?? next)!.day]} · {(current ?? next)!.startTime}–{(current ?? next)!.endTime}</small>}</div></section>
    <div className="schedule-toolbar"><div><button className="secondary-button" onClick={() => setSelectedDay((selectedDay + 6) % 7)}><ChevronLeft /></button><strong>{DAYS[selectedDay]}</strong><button className="secondary-button" onClick={() => setSelectedDay((selectedDay + 1) % 7)}><ChevronRight /></button></div><div><button className="text-button" disabled={!dayEntries.length} onClick={copyDay}><Copy /> Copiar dia</button><button className="text-button danger" disabled={!dayEntries.length} onClick={clearDay}>Limpar dia</button><button className="text-button danger clear-week" disabled={!data.scheduleEntries.length} onClick={clearWeek}>Limpar semana</button><button className="primary-button" onClick={() => openNew()}><Plus /> Novo bloco</button></div></div>
    <section className="schedule-week" aria-label="Cronograma semanal">{DAYS.map((day, index) => <div className={`schedule-day ${index === today ? "today" : ""}`} key={day}><header onClick={() => setSelectedDay(index)}><span>{day.slice(0, 3)}</span><small>{ordered.filter((item) => item.day === index).length} blocos</small></header><div className="schedule-day-list">{ordered.filter((item) => item.day === index).map((entry) => <article className={`schedule-block ${entry.category} ${current?.id === entry.id ? "is-now" : ""}`} key={entry.id} onClick={() => openEdit(entry)}><time>{entry.startTime} — {entry.endTime}{current?.id === entry.id && <b>AGORA</b>}</time><strong>{entry.title}</strong><span>{entry.subjectId ? subjectName(data, entry.subjectId) : CATEGORIES.find((item) => item.id === entry.category)?.label}</span><div><button title="Duplicar para o dia seguinte" onClick={(event) => { event.stopPropagation(); duplicate(entry); }}><Copy /></button><button title="Editar"><Edit3 /></button><button className="danger" title="Excluir" onClick={(event) => { event.stopPropagation(); remove(entry.id); }}><Trash2 /></button></div></article>)}<button className="schedule-add-day" onClick={() => openNew(index)}><Plus /> Adicionar</button></div></div>)}</section>
    <section className="schedule-mobile"><div className="schedule-day-tabs">{DAYS.map((day, index) => <button className={selectedDay === index ? "active" : ""} onClick={() => setSelectedDay(index)} key={day}>{day.slice(0, 3)}</button>)}</div><div className="schedule-agenda">{dayEntries.length ? dayEntries.map((entry) => <article className={entry.category} key={entry.id} onClick={() => openEdit(entry)}><time>{entry.startTime}<span>{entry.endTime}</span></time><div><strong>{entry.title}</strong><small>{entry.subjectId ? subjectName(data, entry.subjectId) : CATEGORIES.find((item) => item.id === entry.category)?.label}</small></div><Edit3 /></article>) : <div className="empty-state compact"><CalendarClock /><strong>Dia livre</strong><p>Adicione um bloco quando quiser planejar este dia.</p></div>}</div></section>
    {draft && <div className="modal-backdrop"><section className="modal schedule-editor"><header><div><span className="eyebrow">{editing ? "EDITAR BLOCO" : "NOVO BLOCO"}</span><h2>{editing ? "Ajuste seu plano" : "Reserve este momento"}</h2></div><button className="icon-button" onClick={() => setDraft(undefined)}><X /></button></header><div className="modal-form"><label>Título<input autoFocus maxLength={LIMITS.scheduleTitle} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Ex.: Revisão de matemática" /></label><label>Categoria<select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value as ScheduleCategory })}>{CATEGORIES.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label>Início<input type="time" value={draft.startTime} onChange={(event) => setDraft({ ...draft, startTime: event.target.value })} /></label><label>Fim<input type="time" value={draft.endTime} onChange={(event) => setDraft({ ...draft, endTime: event.target.value })} /></label><label>Matéria <small>opcional</small><select value={draft.subjectId} onChange={(event) => setDraft({ ...draft, subjectId: event.target.value })}><option value="">Geral</option>{data.subjects.map((subject) => <option value={subject.id} key={subject.id}>{subject.title}</option>)}</select></label><label className="wide">Observações <small>opcional</small><textarea maxLength={LIMITS.scheduleDescription} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="Objetivo, material ou lembrete..." /></label>{!editing && <fieldset className="schedule-days wide"><legend>Repetir nos dias</legend>{DAYS.map((day, index) => <button type="button" className={draft.days.includes(index) ? "active" : ""} onClick={() => setDraft({ ...draft, days: draft.days.includes(index) ? draft.days.filter((item) => item !== index) : [...draft.days, index] })} key={day}>{day.slice(0, 3)}</button>)}</fieldset>}</div><footer><button className="secondary-button" onClick={() => setDraft(undefined)}>Cancelar</button><button className="primary-button" disabled={!draft.title.trim() || !draft.days.length} onClick={save}><Clock3 /> Salvar no cronograma</button></footer></section></div>}
  </main>;
}
export default Cronograma;
