import { CalendarDays, Plus, Trash2, Users, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import type { Team } from "../data";
type Props = { teams: Team[]; onAdd: (team: Omit<Team, "id">) => void; onRemove: (id: string) => void };
function Equipes({ teams, onAdd, onRemove }: Props) {
  const [showForm, setShowForm] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const members = String(form.get("members")).split(",").map((item) => item.trim()).filter(Boolean); onAdd({ name: String(form.get("name")).trim(), subject: String(form.get("subject")).trim(), nextMeeting: String(form.get("nextMeeting")).trim(), members }); event.currentTarget.reset(); setShowForm(false); };
  const initials = (name: string) => name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  return <main className="page"><div className="page-toolbar"><p className="muted">Organize seus grupos e registre os próximos encontros.</p><button className="primary-button" onClick={() => setShowForm(!showForm)}>{showForm ? <X size={18} /> : <Plus size={18} />} {showForm ? "Cancelar" : "Criar equipe"}</button></div>{showForm && <form className="inline-form panel team-form" onSubmit={submit}><label>Nome da equipe<input name="name" maxLength={60} required /></label><label>Matéria<input name="subject" maxLength={60} required /></label><label>Participantes<input name="members" placeholder="Ana, João, Maria" /></label><label>Próximo encontro<input name="nextMeeting" placeholder="Ex.: 25/08 às 14h" /></label><button className="primary-button">Criar</button></form>}<section className="team-grid">{teams.map((team) => <article className="panel team-card" key={team.id}><button className="icon-button team-delete" aria-label={`Excluir ${team.name}`} onClick={() => window.confirm(`Excluir a equipe “${team.name}”?`) && onRemove(team.id)}><Trash2 size={17} /></button><div className="team-icon"><Users /></div><span className="eyebrow">{team.subject}</span><h3>{team.name}</h3><p><CalendarDays size={16} /> {team.nextMeeting || "Nenhum encontro agendado"}</p><div className="team-footer"><div className="avatar-stack">{team.members.length ? team.members.map((member) => <span title={member} key={member}>{initials(member)}</span>) : <small>Nenhum participante</small>}</div><small>{team.members.length} {team.members.length === 1 ? "pessoa" : "pessoas"}</small></div></article>)}{!teams.length && <div className="empty-state panel empty-wide"><Users /><h3>Nenhuma equipe criada</h3><p>Crie uma equipe para organizar seus grupos de estudo.</p><button className="primary-button" onClick={() => setShowForm(true)}><Plus size={18} /> Criar primeira equipe</button></div>}</section></main>;
}
export default Equipes;
