import { CheckCircle2, Plus, RotateCw, Sparkles } from "lucide-react";
import { useState, type FormEvent } from "react";
import type { Flashcard } from "../data";
type Props = { cards: Flashcard[]; onAdd: (card: Omit<Flashcard, "id" | "mastered">) => void; onToggleMastered: (id: string) => void };
function Flashcards({ cards, onAdd, onToggleMastered }: Props) {
  const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const [showForm, setShowForm] = useState(false); const card = cards[index % Math.max(cards.length, 1)];
  const next = () => { setIndex((value) => (value + 1) % cards.length); setFlipped(false); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); onAdd({ question: String(form.get("question")), answer: String(form.get("answer")), subject: String(form.get("subject")) }); event.currentTarget.reset(); setShowForm(false); };
  return <main className="page"><div className="page-toolbar"><div><span className="eyebrow">BARALHO GERAL</span><p className="muted">{cards.filter((item) => item.mastered).length} de {cards.length} dominados</p></div><button className="primary-button" onClick={() => setShowForm(!showForm)}><Plus size={18} /> Novo cartão</button></div>{showForm && <form className="inline-form panel card-form" onSubmit={submit}><label>Matéria<input name="subject" required /></label><label>Pergunta<input name="question" required /></label><label>Resposta<input name="answer" required /></label><button className="primary-button">Criar cartão</button></form>}{card ? <section className="study-area"><button className={`flashcard ${flipped ? "flipped" : ""}`} onClick={() => setFlipped(!flipped)}><span className="eyebrow">{flipped ? "RESPOSTA" : card.subject.toUpperCase()}</span><strong>{flipped ? card.answer : card.question}</strong><small><RotateCw size={15} /> Clique para virar</small></button><div className="study-actions"><button className="secondary-button" onClick={next}>Ainda estudando</button><button className={`primary-button ${card.mastered ? "mastered" : ""}`} onClick={() => { onToggleMastered(card.id); next(); }}><CheckCircle2 size={18} /> {card.mastered ? "Revisar novamente" : "Já sei"}</button></div><p className="card-position">Cartão {index + 1} de {cards.length}</p></section> : <div className="empty-state panel"><Sparkles /><p>Crie seu primeiro cartão para começar.</p></div>}</main>;
}
export default Flashcards;
