import { CheckCircle2, Layers3, Plus, RotateCw, Sparkles, Trash2 } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { LIMITS, type Flashcard, type Subject } from "../data";
type Props = { cards: Flashcard[]; subjects: Subject[]; fixedSubject?: Subject; onAdd: (card: Omit<Flashcard, "id" | "mastered">) => void; onToggleMastered: (id: string) => void; onRemove: (id: string) => void };
function Flashcards({ cards, subjects, fixedSubject, onAdd, onToggleMastered, onRemove }: Props) {
  const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const [showForm, setShowForm] = useState(false); const [deck, setDeck] = useState("Todos");
  const decks = useMemo(() => ["Todos", ...new Set(cards.map((item) => item.deck || "Geral"))], [cards]); const visible = deck === "Todos" ? cards : cards.filter((item) => (item.deck || "Geral") === deck); const card = visible[index % Math.max(visible.length, 1)];
  const next = () => { if (visible.length) setIndex((value) => (value + 1) % visible.length); setFlipped(false); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const subjectId = fixedSubject?.id || String(form.get("subjectId") || "") || undefined; const subject = fixedSubject?.title || subjects.find((item) => item.id === subjectId)?.title || "Geral"; onAdd({ question: String(form.get("question")).trim(), answer: String(form.get("answer")).trim(), subject, subjectId, deck: String(form.get("deck")).trim() || "Geral" }); event.currentTarget.reset(); setShowForm(false); };
  return <main className={fixedSubject ? "cards-content" : "page"}><div className="page-toolbar"><div><span className="eyebrow">{fixedSubject ? `FLASHCARDS · ${fixedSubject.title.toUpperCase()}` : "TODOS OS FLASHCARDS"}</span><p className="muted">{cards.filter((item) => item.mastered).length} de {cards.length} dominados</p></div><button className="primary-button" disabled={cards.length >= (fixedSubject ? LIMITS.flashcardsPerSubject : LIMITS.flashcards)} onClick={() => setShowForm(!showForm)}><Plus size={18} /> Novo cartão</button></div>{decks.length > 1 && <div className="deck-filter"><Layers3 size={16} />{decks.map((item) => <button className={deck === item ? "active" : ""} onClick={() => { setDeck(item); setIndex(0); }} key={item}>{item}</button>)}</div>}{showForm && <form className="inline-form panel card-form advanced" onSubmit={submit}>{!fixedSubject && <label>Matéria<select name="subjectId"><option value="">Geral</option>{subjects.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label>}<label>Bloco<input name="deck" maxLength={80} placeholder="Geral" /></label><label>Pergunta<input name="question" maxLength={1000} required /></label><label>Resposta<input name="answer" maxLength={5000} required /></label><button className="primary-button">Criar cartão</button></form>}{card ? <section className="study-area"><button className={`flashcard ${flipped ? "flipped" : ""}`} onClick={() => setFlipped(!flipped)}><span className="eyebrow">{flipped ? "RESPOSTA" : `${card.subject.toUpperCase()} · ${(card.deck || "Geral").toUpperCase()}`}</span><strong>{flipped ? card.answer : card.question}</strong><small><RotateCw size={15} /> Clique para virar</small></button><div className="study-actions"><button className="secondary-button danger-outline" onClick={() => { if (window.confirm("Excluir este cartão?")) { onRemove(card.id); setIndex(0); setFlipped(false); } }}><Trash2 size={17} /> Excluir</button><button className="secondary-button" onClick={next}>Ainda estudando</button><button className="primary-button" onClick={() => { onToggleMastered(card.id); next(); }}><CheckCircle2 size={18} /> {card.mastered ? "Revisar novamente" : "Já sei"}</button></div><p className="card-position">Cartão {index + 1} de {visible.length}</p></section> : <div className="empty-state panel"><Sparkles /><h3>Nenhum flashcard</h3><p>Crie seu primeiro cartão para começar a revisar.</p><button className="primary-button" onClick={() => setShowForm(true)}><Plus size={18} /> Criar cartão</button></div>}</main>;
}
export default Flashcards;
