import { ArrowRight, BookOpen, CheckCircle2, Clock3, Flame, GraduationCap, Timer } from "lucide-react";
import type { PageId } from "../components/Navbar";
import { TaskRow } from "../components/TaskRow";
import { formatTimer, type AppData } from "../data";
type Props = { data: AppData; onNavigate: (page: PageId) => void; onOpenSubject: (id: string) => void; onToggleTask: (id: string) => void };
function Home({ data, onNavigate, onOpenSubject, onToggleTask }: Props) {
  const pending = data.tasks.filter((task) => !task.completed).sort((a, b) => a.dueDate.localeCompare(b.dueDate)); const completed = data.tasks.filter((task) => task.completed).length; const progress = data.tasks.length ? Math.round(completed / data.tasks.length * 100) : 0; const globalTimer = data.timers.find((item) => item.scope === "global"); const totalSeconds = data.stats.reduce((sum, item) => sum + item.focusedSeconds, 0);
  const formatDate = (value: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(`${value}T12:00:00`));
  return <main className="page">{globalTimer && <button className="global-timer-strip" onClick={() => onNavigate("timer")}><Timer size={18} /><span><strong>{globalTimer.type === "pomodoro" ? "Sua sessão geral está pronta" : "Cronômetro geral salvo"}</strong><small>{formatTimer(globalTimer.type === "pomodoro" ? globalTimer.remainingSeconds : globalTimer.elapsedSeconds, globalTimer.type === "stopwatch")} · {globalTimer.status === "running" ? "em andamento" : "pausado"}</small></span><ArrowRight /></button>}<section className="welcome-card"><div><span className="eyebrow"><Flame size={15} /> SEU RITMO, DO SEU JEITO</span><h2>Um pouco de foco hoje<br />faz uma grande diferença.</h2><p>Você já registrou <strong>{Math.floor(totalSeconds / 3600)}h {Math.floor(totalSeconds % 3600 / 60)}min</strong> de estudo focado.</p><button className="primary-button" onClick={() => onNavigate("timer")}><Timer size={18} /> Estudar agora</button></div><div className="progress-ring" style={{ "--progress": `${progress * 3.6}deg` } as React.CSSProperties}><div><strong>{progress}%</strong><span>tarefas concluídas</span></div></div></section><section className="stats-grid"><article className="stat-card"><span className="stat-icon orange"><Clock3 /></span><div><small>Próxima entrega</small><strong>{pending[0] ? formatDate(pending[0].dueDate) : "Tudo em dia"}</strong></div></article><article className="stat-card"><span className="stat-icon blue"><BookOpen /></span><div><small>Flashcards</small><strong>{data.flashcards.length} cartões</strong></div></article><article className="stat-card"><span className="stat-icon green"><GraduationCap /></span><div><small>Matérias</small><strong>{data.subjects.length} criadas</strong></div></article></section>
  {data.subjects.length > 0 && <section className="panel recent-subjects"><div className="panel-heading"><div><span className="eyebrow">SEUS ESPAÇOS</span><h3>Matérias recentes</h3></div><button className="text-button" onClick={() => onNavigate("subjects")}>Ver todas <ArrowRight size={16} /></button></div><div>{data.subjects.slice(-4).reverse().map((subject) => { const waiting = data.tasks.filter((item) => item.subjectId === subject.id && !item.completed).length; return <button style={{ "--subject-color": subject.color } as React.CSSProperties} onClick={() => onOpenSubject(subject.id)} key={subject.id}><span className="subject-dot" /><strong>{subject.title}</strong><small>{waiting} tarefas pendentes</small><ArrowRight /></button>; })}</div></section>}
  <section className="dashboard-grid"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">AGENDA</span><h3>Seus próximos prazos</h3></div><button className="text-button" onClick={() => onNavigate("prazos")}>Ver todos <ArrowRight size={16} /></button></div><div className="task-list">{pending.slice(0, 3).map((task) => <TaskRow key={task.id} task={task} onToggle={onToggleTask} compact />)}{!pending.length && <div className="empty-state"><CheckCircle2 /><p>Nenhuma tarefa pendente.</p></div>}</div></article><article className="panel quick-panel"><div className="panel-heading"><div><span className="eyebrow">ATALHOS</span><h3>O que vamos fazer?</h3></div></div><button onClick={() => onNavigate("subjects")}><GraduationCap /><span><strong>Abrir matérias</strong><small>Continue uma matéria específica</small></span><ArrowRight /></button><button onClick={() => onNavigate("flashcards")}><BookOpen /><span><strong>Revisar cartões</strong><small>Veja todos os seus flashcards</small></span><ArrowRight /></button></article></section></main>;
}
export default Home;
