import { Camera, Check, Database, Download, GraduationCap, ImageOff, ShieldCheck, Sparkles, Target, Upload } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import type { AppData, Profile, ThemeId } from "../data";
import { processAvatar } from "../imageUtils";
import { downloadBackup, readBackup, storageUsage } from "../storage";

type Props = { data: AppData; onSave: (profile: Profile) => void; onTheme: (theme: ThemeId) => void; onImport: (data: AppData) => void };
const themes: { id: ThemeId; name: string; description: string; colors: string[]; dark?: boolean }[] = [
  { id: "omnidesk", name: "OmniDesk Clássico", description: "Azul-marinho, marfim e laranja pastel.", colors: ["#1e2d4c", "#ec996a", "#f3f3ee", "#ffffff"] },
  { id: "sage", name: "Sálvia Serena", description: "Verdes tranquilos e creme acolhedor.", colors: ["#38574c", "#d49a78", "#f3f1e8", "#fbfaf4"] },
  { id: "aurora", name: "Aurora Pastel", description: "Lavanda, areia e rosa suave.", colors: ["#4d496f", "#d58d91", "#f5f0ed", "#fffaf7"] },
  { id: "atlantic", name: "Noite Atlântica", description: "Azul profundo com detalhes luminosos.", colors: ["#dbe4e0", "#e7a27b", "#121b2b", "#1b2940"], dark: true },
  { id: "plum", name: "Ameixa Noturna", description: "Ameixa, lavanda e pêssego pastel.", colors: ["#eee5ec", "#dca090", "#211923", "#302434"], dark: true },
];

function Perfil({ data, onSave, onTheme, onImport }: Props) {
  const [message, setMessage] = useState(""); const fileInput = useRef<HTMLInputElement>(null); const avatarInput = useRef<HTMLInputElement>(null);
  const [usage, setUsage] = useState<{ usage?: number; quota?: number }>({}); const [processingAvatar, setProcessingAvatar] = useState(false);
  useEffect(() => { void storageUsage().then((estimate) => setUsage({ usage: estimate.usage, quota: estimate.quota })); }, []);
  const notify = (value: string) => { setMessage(value); window.setTimeout(() => setMessage(""), 2800); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ ...data.profile, name: String(form.get("name")).trim(), course: String(form.get("course")).trim(), objective: String(form.get("objective")).trim(), weeklyGoal: Number(form.get("weeklyGoal")) }); notify("Alterações salvas."); };
  const changeAvatar = async (file?: File) => { if (!file) return; setProcessingAvatar(true); try { const avatar = await processAvatar(file); onSave({ ...data.profile, avatar }); notify("Imagem de perfil atualizada."); } catch (reason) { notify(reason instanceof Error ? reason.message : "Não foi possível alterar a imagem."); } finally { setProcessingAvatar(false); if (avatarInput.current) avatarInput.current.value = ""; } };
  const importFile = async (file?: File) => { if (!file) return; try { const backup = await readBackup(file); if (!window.confirm("A importação substituirá todos os dados atuais. Deseja continuar?")) return; onImport(backup); notify("Backup restaurado com sucesso."); } catch (reason) { notify(reason instanceof Error ? reason.message : "Falha ao importar o backup."); } finally { if (fileInput.current) fileInput.current.value = ""; } };
  const initials = data.profile.name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  return <main className="page profile-page"><section className="panel profile-card"><div className="profile-cover" /><div className="profile-summary"><div className="profile-avatar">{data.profile.avatar ? <img src={data.profile.avatar} alt="Imagem de perfil" /> : initials}<input ref={avatarInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => changeAvatar(event.target.files?.[0])} /><button type="button" disabled={processingAvatar} onClick={() => avatarInput.current?.click()} aria-label="Trocar imagem de perfil"><Camera size={14} /></button></div><div><h2>{data.profile.name}</h2><p>{data.profile.course}</p>{data.profile.objective && <small>{data.profile.objective}</small>}</div><div className="avatar-actions"><button className="secondary-button" disabled={processingAvatar} onClick={() => avatarInput.current?.click()}><Camera size={16} /> {processingAvatar ? "Processando..." : data.profile.avatar ? "Trocar imagem" : "Adicionar imagem"}</button>{data.profile.avatar && <button className="text-button danger" onClick={() => { onSave({ ...data.profile, avatar: undefined }); notify("Imagem removida."); }}><ImageOff size={16} /> Remover</button>}</div></div><form className="profile-form" onSubmit={submit}><label><span><GraduationCap size={17} /> Nome</span><input name="name" defaultValue={data.profile.name} maxLength={60} required /></label><label><span><GraduationCap size={17} /> Curso ou área de estudo</span><input name="course" defaultValue={data.profile.course} maxLength={80} required /></label><label className="profile-objective"><span><Sparkles size={17} /> Objetivo atual <i className="optional">opcional</i></span><input name="objective" defaultValue={data.profile.objective} maxLength={160} placeholder="Ex.: concluir a graduação" /></label><label><span><Target size={17} /> Meta semanal de estudo</span><span className="input-with-unit"><input type="number" min="1" max="80" name="weeklyGoal" defaultValue={data.profile.weeklyGoal} required /><strong>horas</strong></span></label><button className="primary-button" type="submit"><Check size={18} /> Salvar alterações</button>{message && <p className="save-message" role="status">{message}</p>}</form></section>
  <section className="panel appearance-panel"><div className="data-panel-heading"><span className="stat-icon purple"><Sparkles /></span><div><h3>Aparência</h3><p>Escolha uma atmosfera para o seu espaço. A preferência é aplicada imediatamente.</p></div></div><div className="theme-grid">{themes.map((theme) => <button className={`theme-option ${data.theme === theme.id ? "selected" : ""}`} onClick={() => onTheme(theme.id)} aria-pressed={data.theme === theme.id} key={theme.id}><span className="theme-preview" style={{ background: theme.colors[2] }}><i style={{ background: theme.colors[0] }} /><i style={{ background: theme.colors[3] }} /><i style={{ background: theme.colors[1] }} /></span><span><strong>{theme.name}</strong><small>{theme.description}</small></span>{data.theme === theme.id && <Check size={17} />}{theme.dark && <em>ESCURO</em>}</button>)}</div></section>
  <section className="panel data-panel"><div className="data-panel-heading"><span className="stat-icon blue"><Database /></span><div><h3>Seus dados</h3><p>Crie uma cópia para restaurar seus estudos neste ou em outro dispositivo.</p></div></div><div className="privacy-line"><ShieldCheck size={17} /> Seus dados permanecem apenas neste navegador até você exportá-los.</div>{usage.quota && <div className="storage-meter"><div><span>Armazenamento local</span><strong>{((usage.usage ?? 0) / 1024 / 1024).toFixed(1)} MB usados</strong></div><progress value={usage.usage ?? 0} max={usage.quota} /><small>A aplicação avisará antes de se aproximar do limite do navegador.</small></div>}<div className="backup-actions"><button className="primary-button" onClick={() => downloadBackup(data)}><Download size={18} /> Exportar backup</button><input ref={fileInput} hidden type="file" accept="application/json,.json" onChange={(event) => importFile(event.target.files?.[0])} /><button className="secondary-button" onClick={() => fileInput.current?.click()}><Upload size={18} /> Importar backup</button></div></section></main>;
}
export default Perfil;
