import { Check, Database, Download, GraduationCap, Mail, ShieldCheck, Target, Upload } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import type { AppData, Profile } from "../data";
import { downloadBackup, readBackup, storageUsage } from "../storage";

type Props = { data: AppData; onSave: (profile: Profile) => void; onImport: (data: AppData) => void };
function Perfil({ data, onSave, onImport }: Props) {
  const [message, setMessage] = useState(""); const fileInput = useRef<HTMLInputElement>(null);
  const [usage, setUsage] = useState<{ usage?: number; quota?: number }>({});
  useEffect(() => { void storageUsage().then((estimate) => setUsage({ usage: estimate.usage, quota: estimate.quota })); }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ name: String(form.get("name")).trim(), email: String(form.get("email")).trim(), course: String(form.get("course")).trim(), weeklyGoal: Number(form.get("weeklyGoal")) }); setMessage("Alterações salvas."); window.setTimeout(() => setMessage(""), 2500); };
  const importFile = async (file?: File) => { if (!file) return; try { const backup = await readBackup(file); if (!window.confirm("A importação substituirá todos os dados atuais. Deseja continuar?")) return; onImport(backup); setMessage("Backup restaurado com sucesso."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Falha ao importar o backup."); } finally { if (fileInput.current) fileInput.current.value = ""; } };
  const initials = data.profile.name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  return <main className="page profile-page"><section className="panel profile-card"><div className="profile-cover" /><div className="profile-summary"><div className="profile-avatar">{initials}</div><div><h2>{data.profile.name}</h2><p>{data.profile.course}</p></div></div><form className="profile-form" onSubmit={submit}><label><span><GraduationCap size={17} /> Nome</span><input name="name" defaultValue={data.profile.name} maxLength={60} required /></label><label><span><Mail size={17} /> E-mail</span><input type="email" name="email" defaultValue={data.profile.email} /></label><label><span><GraduationCap size={17} /> Curso</span><input name="course" defaultValue={data.profile.course} maxLength={80} required /></label><label><span><Target size={17} /> Meta semanal (horas)</span><input type="number" min="1" max="80" name="weeklyGoal" defaultValue={data.profile.weeklyGoal} required /></label><button className="primary-button" type="submit"><Check size={18} /> Salvar alterações</button>{message && <p className="save-message" role="status">{message}</p>}</form></section>
  <section className="panel data-panel"><div className="data-panel-heading"><span className="stat-icon blue"><Database /></span><div><h3>Seus dados</h3><p>Crie uma cópia para restaurar seus estudos neste ou em outro dispositivo.</p></div></div><div className="privacy-line"><ShieldCheck size={17} /> Seus dados permanecem apenas neste navegador até você exportá-los.</div>{usage.quota && <div className="storage-meter"><div><span>Armazenamento local</span><strong>{((usage.usage ?? 0) / 1024 / 1024).toFixed(1)} MB usados</strong></div><progress value={usage.usage ?? 0} max={usage.quota} /><small>A aplicação avisará antes de se aproximar do limite do navegador.</small></div>}<div className="backup-actions"><button className="primary-button" onClick={() => downloadBackup(data)}><Download size={18} /> Exportar backup</button><input ref={fileInput} hidden type="file" accept="application/json,.json" onChange={(event) => importFile(event.target.files?.[0])} /><button className="secondary-button" onClick={() => fileInput.current?.click()}><Upload size={18} /> Importar backup</button></div></section></main>;
}
export default Perfil;
