import { BriefcaseBusiness, CalendarPlus, CheckCircle2, Trash2 } from "lucide-react";
import { useState, type FormEvent } from "react";
import { LIMITS, subjectName, type AppData, type Assignment } from "../data";
type Props = { data: AppData; mutate: (updater: (data: AppData) => AppData) => void };
function Prazos({ data, mutate }: Props) {
  const [showForm, setShowForm] = useState(false); const [filter, setFilter] = useState<"Todos" | "Pendentes" | "Concluídos">("Todos");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const subjectId = String(form.get("subjectId")); if (!subjectId || data.assignments.length >= LIMITS.assignments || data.assignments.filter((item) => item.subjectId === subjectId).length >= LIMITS.assignmentsPerSubject) return; mutate((current) => ({ ...current, assignments: [{ id: crypto.randomUUID(), subjectId, title: String(form.get("title")).trim(), description: String(form.get("description")).trim(), dueDate: String(form.get("dueDate")), priority: String(form.get("priority")) as Assignment["priority"], completed: false }, ...current.assignments] })); setShowForm(false); };
  const assignments = data.assignments.filter((item) => filter === "Todos" || (filter === "Pendentes" ? !item.completed : item.completed)).sort((a, b) => a.dueDate.localeCompare(b.dueDate));
  return <main className="page"><div className="page-toolbar"><div><span className="eyebrow">PROJETOS E ENTREGAS</span><p className="muted">{data.assignments.length} {data.assignments.length === 1 ? "trabalho cadastrado" : "trabalhos cadastrados"}</p></div><button className="primary-button" disabled={!data.subjects.length} onClick={() => setShowForm(!showForm)}><CalendarPlus size={18} /> Novo trabalho</button></div><div className="simple-filters">{(["Todos", "Pendentes", "Concluídos"] as const).map((item) => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div>{showForm && <form className="inline-form panel global-deadline-form" onSubmit={submit}><label>Título<input name="title" maxLength={LIMITS.title} required autoFocus /></label><label>Matéria<select name="subjectId" required><option value="">Selecione</option>{data.subjects.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Descrição<input name="description" maxLength={10_000} /></label><label>Entrega<input name="dueDate" type="date" required /></label><label>Prioridade<select name="priority"><option>Média</option><option>Alta</option><option>Baixa</option></select></label><button className="primary-button">Adicionar</button></form>}<section className="panel"><div className="panel-heading"><div><span className="eyebrow">VISÃO GERAL</span><h3>{assignments.length} {assignments.length === 1 ? "trabalho" : "trabalhos"}</h3></div></div><div className="task-list full">{assignments.map((item) => <div className={`assignment-row ${item.completed ? "completed" : ""}`} key={item.id}><button className="check-button" onClick={() => mutate((current) => ({ ...current, assignments: current.assignments.map((entry) => entry.id === item.id ? { ...entry, completed: !entry.completed } : entry) }))}>{item.completed && <CheckCircle2 size={14} />}</button><div><strong>{item.title}</strong><small>{subjectName(data, item.subjectId)} · {item.description || "Sem descrição"}</small></div><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span><time>{new Date(`${item.dueDate}T12:00`).toLocaleDateString("pt-BR")}</time><button className="icon-button danger" onClick={() => window.confirm(`Excluir “${item.title}”?`) && mutate((current) => ({ ...current, assignments: current.assignments.filter((entry) => entry.id !== item.id) }))}><Trash2 size={17} /></button></div>)}{!assignments.length && <div className="empty-state"><BriefcaseBusiness /><h3>Nenhum trabalho neste filtro</h3><p>Cadastre projetos, provas e entregas importantes.</p></div>}</div></section></main>;
}
export default Prazos;
