import { BriefcaseBusiness, CalendarPlus, ListTodo } from "lucide-react";
import { useState, type FormEvent } from "react";
import { TaskRow } from "../components/TaskRow";
import { LIMITS, subjectName, type AppData, type Assignment, type Task } from "../data";
type Props = { data: AppData; mutate: (updater: (data: AppData) => AppData) => void; onAdd: (task: Omit<Task, "id" | "completed">) => void; onToggle: (id: string) => void; onRemove: (id: string) => void };
function Prazos({ data, mutate, onAdd, onToggle, onRemove }: Props) {
  const [type, setType] = useState<"tasks" | "assignments">("tasks"); const [showForm, setShowForm] = useState(false); const [filter, setFilter] = useState<"Todos" | "Pendentes" | "Concluídos">("Todos");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const subjectId = String(form.get("subjectId") || "") || undefined; if (type === "tasks") onAdd({ title: String(form.get("title")).trim(), subject: subjectName(data, subjectId), subjectId, dueDate: String(form.get("dueDate")), priority: String(form.get("priority")) as Task["priority"] }); else if (subjectId && data.assignments.length < LIMITS.assignments && data.assignments.filter((item) => item.subjectId === subjectId).length < LIMITS.assignmentsPerSubject) mutate((current) => ({ ...current, assignments: [{ id: crypto.randomUUID(), subjectId, title: String(form.get("title")).trim(), description: String(form.get("description")).trim(), dueDate: String(form.get("dueDate")), priority: String(form.get("priority")) as Assignment["priority"], completed: false }, ...current.assignments] })); setShowForm(false); };
  const tasks = data.tasks.filter((item) => filter === "Todos" || (filter === "Pendentes" ? !item.completed : item.completed)).sort((a, b) => a.dueDate.localeCompare(b.dueDate)); const assignments = data.assignments.filter((item) => filter === "Todos" || (filter === "Pendentes" ? !item.completed : item.completed)).sort((a, b) => a.dueDate.localeCompare(b.dueDate)); const visibleCount = type === "tasks" ? tasks.length : assignments.length;
  return <main className="page"><div className="page-toolbar"><div className="content-kind-tabs"><button className={type === "tasks" ? "active" : ""} onClick={() => setType("tasks")}><ListTodo size={17} /> Tarefas</button><button className={type === "assignments" ? "active" : ""} onClick={() => setType("assignments")}><BriefcaseBusiness size={17} /> Trabalhos</button></div><button className="primary-button" onClick={() => setShowForm(!showForm)}><CalendarPlus size={18} /> Novo {type === "tasks" ? "prazo" : "trabalho"}</button></div><div className="simple-filters">{(["Todos", "Pendentes", "Concluídos"] as const).map((item) => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div>{showForm && <form className="inline-form panel global-deadline-form" onSubmit={submit}><label>Título<input name="title" maxLength={LIMITS.title} required autoFocus /></label><label>Matéria<select name="subjectId" required={type === "assignments"}><option value="">{type === "tasks" ? "Geral" : "Selecione"}</option>{data.subjects.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label>{type === "assignments" && <label>Descrição<input name="description" maxLength={10_000} /></label>}<label>Entrega<input name="dueDate" type="date" required /></label><label>Prioridade<select name="priority"><option>Média</option><option>Alta</option><option>Baixa</option></select></label><button className="primary-button">Adicionar</button></form>}<section className="panel"><div className="panel-heading"><div><span className="eyebrow">VISÃO GERAL</span><h3>{visibleCount} {type === "tasks" ? "tarefas" : "trabalhos"}</h3></div></div><div className="task-list full">{type === "tasks" ? tasks.map((task) => <TaskRow task={task} onToggle={onToggle} onRemove={onRemove} key={task.id} />) : assignments.map((item) => <div className={`assignment-row ${item.completed ? "completed" : ""}`} key={item.id}><button className="check-button" onClick={() => mutate((current) => ({ ...current, assignments: current.assignments.map((entry) => entry.id === item.id ? { ...entry, completed: !entry.completed } : entry) }))}>{item.completed && <span>✓</span>}</button><div><strong>{item.title}</strong><small>{subjectName(data, item.subjectId)} · {item.description || "Sem descrição"}</small></div><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span><time>{new Date(`${item.dueDate}T12:00`).toLocaleDateString("pt-BR")}</time><button className="icon-button danger" onClick={() => mutate((current) => ({ ...current, assignments: current.assignments.filter((entry) => entry.id !== item.id) }))}>×</button></div>)}{!visibleCount && <p className="empty-copy">Nenhum item neste filtro.</p>}</div></section></main>;
}
export default Prazos;
