/* eslint-disable @typescript-eslint/no-unused-expressions */
import { CheckCircle2, ChevronLeft, ChevronRight, CircleHelp, FileInput, Pencil, Play, Plus, Search, Shuffle, Trash2, XCircle } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { LIMITS, subjectName, type AppData, type Question, type SimulationAttempt } from "../data";
import { parseQuestionsText, QUESTION_IMPORT_EXAMPLE, type QuestionParseResult } from "../questionParser";

type Props = { data: AppData; mutate: (updater: (data: AppData) => AppData) => void; fixedSubjectId?: string; embedded?: boolean; onContextChange?: (segments: string[]) => void };
type Tab = "bank" | "simulations" | "history";
const shuffled = <T,>(values: T[]) => { const result = [...values]; for (let i = result.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [result[i], result[j]] = [result[j], result[i]]; } return result; };
const now = () => new Date().toISOString();
const resultTone = (attempt: SimulationAttempt) => attempt.status !== "completed" ? "pending" : (attempt.score ?? 0) < attempt.passingScore ? "failed" : (attempt.score ?? 0) < attempt.passingScore + 1 ? "near" : "passed";
const confirmBulk = (count: number, action: string) => window.confirm(`${action} ${count} questões selecionadas?`) && window.confirm("Esta alteração em massa pode afetar modelos de simulados. Confirma novamente?");

function Questoes({ data, mutate, fixedSubjectId, embedded, onContextChange }: Props) {
  const [tab, setTab] = useState<Tab>("bank"); const [search, setSearch] = useState(""); const [subjectFilter, setSubjectFilter] = useState(fixedSubjectId ?? "all");
  const [collection, setCollection] = useState("all"); const [category, setCategory] = useState("all"); const [formOpen, setFormOpen] = useState(false); const [importOpen, setImportOpen] = useState(false);
  const [alternatives, setAlternatives] = useState(["", "", "", ""]); const [editing, setEditing] = useState<Question>(); const [importText, setImportText] = useState(QUESTION_IMPORT_EXAMPLE); const [preview, setPreview] = useState<QuestionParseResult>();
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [activeAttempt, setActiveAttempt] = useState<string>(); const [questionIndex, setQuestionIndex] = useState(0); const [reviewing, setReviewing] = useState<string>(); const [selectionCategory, setSelectionCategory] = useState(""); const [bulkSubject, setBulkSubject] = useState("");
  const collections = [...new Set(data.questions.map((item) => item.collection).filter(Boolean))].sort(); const categories = [...new Set(data.questions.flatMap((item) => item.categories))].sort();
  const questions = useMemo(() => data.questions.filter((item) => (!fixedSubjectId || item.subjectId === fixedSubjectId) && (subjectFilter === "all" || item.subjectId === subjectFilter) && (collection === "all" || item.collection === collection) && (category === "all" || item.categories.includes(category)) && `${item.statement} ${item.collection} ${item.categories.join(" ")} ${item.institution}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))), [data.questions, fixedSubjectId, subjectFilter, collection, category, search]);
  const attempts = data.simulationAttempts.filter((item) => !fixedSubjectId || item.questions.some((question) => question.subjectId === fixedSubjectId));
  const visibleSimulations = data.simulations.filter((simulation) => !fixedSubjectId || simulation.questionIds.some((id) => data.questions.find((question) => question.id === id)?.subjectId === fixedSubjectId));
  const currentAttempt = data.simulationAttempts.find((item) => item.id === activeAttempt && item.status === "in_progress");
  useEffect(() => { const root = tab === "bank" ? "Banco de questões" : tab === "simulations" ? "Simulados" : "Histórico"; onContextChange?.([root, ...(currentAttempt ? ["Em andamento"] : reviewing ? ["Revisão"] : [])]); }, [tab, currentAttempt, reviewing, onContextChange]);

  const resetForm = () => { setEditing(undefined); setAlternatives(["", "", "", ""]); setFormOpen(false); };
  const saveQuestion = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const clean = alternatives.map((text, index) => ({ id: String.fromCharCode(65 + index), text: text.trim() })).filter((item) => item.text); if (clean.length < 2) return; const stamp = now(); const question: Question = { id: editing?.id ?? crypto.randomUUID(), subjectId: fixedSubjectId || String(form.get("subjectId") || "") || undefined, collection: String(form.get("collection") || "Geral").trim() || "Geral", categories: String(form.get("categories") || "").split(",").map((item) => item.trim()).filter(Boolean).slice(0, 12), statement: String(form.get("statement")).trim(), alternatives: clean, correctAlternativeId: String(form.get("answer")), explanation: String(form.get("explanation") || "").trim(), institution: String(form.get("institution") || "").trim(), year: Number(form.get("year")) || undefined, source: String(form.get("source") || "").trim(), createdAt: editing?.createdAt ?? stamp, updatedAt: stamp }; mutate((current) => ({ ...current, questions: editing ? current.questions.map((item) => item.id === question.id ? question : item) : [question, ...current.questions] })); resetForm(); };
  const editQuestion = (question: Question) => { setEditing(question); setAlternatives(question.alternatives.map((item) => item.text)); setFormOpen(true); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const removeQuestion = (id: string) => { if (!window.confirm("Excluir esta questão do banco? Tentativas concluídas serão preservadas.")) return; mutate((current) => ({ ...current, questions: current.questions.filter((item) => item.id !== id), simulations: current.simulations.map((item) => ({ ...item, questionIds: item.questionIds.filter((questionId) => questionId !== id) })) })); setSelected((value) => new Set([...value].filter((item) => item !== id))); };
  const importQuestions = () => { if (!preview?.questions.length || preview.errors.length || data.questions.length + preview.questions.length > LIMITS.questions) return; const stamp = now(); mutate((current) => ({ ...current, questions: [...preview.questions.map((item) => ({ ...item, id: crypto.randomUUID(), createdAt: stamp, updatedAt: stamp })), ...current.questions] })); setImportOpen(false); setPreview(undefined); };
  const createSimulation = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const ids = selected.size ? [...selected] : questions.map((item) => item.id); if (!ids.length || ids.length > LIMITS.simulationQuestions) return; const form = new FormData(event.currentTarget); const stamp = now(); mutate((current) => ({ ...current, simulations: [{ id: crypto.randomUUID(), title: String(form.get("title")).trim(), questionIds: ids, shuffleQuestions: form.get("shuffleQuestions") === "on", shuffleAlternatives: form.get("shuffleAlternatives") === "on", passingScore: Number(form.get("passingScore")) || 5, createdAt: stamp, updatedAt: stamp }, ...current.simulations] })); setSelected(new Set()); event.currentTarget.reset(); };
  const startSimulation = (simulationId: string) => { const simulation = data.simulations.find((item) => item.id === simulationId); if (!simulation) return; let snapshot = simulation.questionIds.map((id) => data.questions.find((item) => item.id === id)).filter(Boolean) as Question[]; if (simulation.shuffleQuestions) snapshot = shuffled(snapshot); if (simulation.shuffleAlternatives) snapshot = snapshot.map((item) => ({ ...item, alternatives: shuffled(item.alternatives) })); if (!snapshot.length) return; const attempt: SimulationAttempt = { id: crypto.randomUUID(), simulationId, title: simulation.title, questions: structuredClone(snapshot), answers: {}, passingScore: simulation.passingScore, status: "in_progress", startedAt: now() }; mutate((current) => ({ ...current, simulationAttempts: [attempt, ...current.simulationAttempts] })); setActiveAttempt(attempt.id); setQuestionIndex(0); };
  const submitAttempt = (attempt: SimulationAttempt) => { const unanswered = attempt.questions.length - Object.keys(attempt.answers).length; if (!window.confirm(unanswered ? `Finalizar com ${unanswered} questão(ões) sem resposta?` : "Finalizar e corrigir o simulado?")) return; const correct = attempt.questions.filter((item) => attempt.answers[item.id] === item.correctAlternativeId).length; const score = Number((correct / attempt.questions.length * 10).toFixed(2)); mutate((current) => ({ ...current, simulationAttempts: current.simulationAttempts.map((item) => item.id === attempt.id ? { ...item, status: "completed", completedAt: now(), score, passed: score >= item.passingScore } : item) })); setActiveAttempt(undefined); setTab("history"); };
  const selectVisible = () => setSelected(new Set(questions.map((item) => item.id))); const selectCategoryItems = () => setSelected(new Set(data.questions.filter((item) => item.categories.includes(selectionCategory) && (!fixedSubjectId || item.subjectId === fixedSubjectId)).map((item) => item.id)));
  const editSelectedCollection = () => { const value = window.prompt("Nova coleção para as questões selecionadas:")?.trim(); if (!value || !selected.size || !confirmBulk(selected.size, "Editar")) return; const stamp = now(); mutate((current) => ({ ...current, questions: current.questions.map((item) => selected.has(item.id) ? { ...item, collection: value.slice(0, 120), updatedAt: stamp } : item) })); };
  const editSelectedCategories = () => { const value = window.prompt("Substitua as categorias selecionadas (separe por vírgulas):")?.trim(); if (value === undefined || !selected.size || !confirmBulk(selected.size, "Editar")) return; const values = value.split(",").map((item) => item.trim()).filter(Boolean).slice(0, 12); const stamp = now(); mutate((current) => ({ ...current, questions: current.questions.map((item) => selected.has(item.id) ? { ...item, categories: values, updatedAt: stamp } : item) })); };
  const moveSelectedSubject = () => { if (!selected.size || !bulkSubject || !confirmBulk(selected.size, "Mover")) return; const subjectId = bulkSubject === "general" ? undefined : bulkSubject; const stamp = now(); mutate((current) => ({ ...current, questions: current.questions.map((item) => selected.has(item.id) ? { ...item, subjectId, updatedAt: stamp } : item) })); setBulkSubject(""); };
  const deleteSelected = () => { if (!selected.size || !confirmBulk(selected.size, "Excluir permanentemente")) return; mutate((current) => ({ ...current, questions: current.questions.filter((item) => !selected.has(item.id)), simulations: current.simulations.map((item) => ({ ...item, questionIds: item.questionIds.filter((id) => !selected.has(id)) })) })); setSelected(new Set()); };

  if (currentAttempt) { const question = currentAttempt.questions[questionIndex]; const answered = Object.keys(currentAttempt.answers).length; return <main className={`${embedded ? "" : "page "}question-area`}><section className="panel attempt-runner"><div className="attempt-head"><div><span className="eyebrow">SIMULADO EM ANDAMENTO</span><h2>{currentAttempt.title}</h2><small>{answered} de {currentAttempt.questions.length} respondidas</small></div><button className="secondary-button" onClick={() => setActiveAttempt(undefined)}>Salvar e sair</button></div><progress value={questionIndex + 1} max={currentAttempt.questions.length} /><article className="attempt-question"><span>Questão {questionIndex + 1}</span><h3>{question.statement}</h3>{question.alternatives.map((alternative) => <label className={currentAttempt.answers[question.id] === alternative.id ? "selected" : ""} key={alternative.id}><input type="radio" name={question.id} checked={currentAttempt.answers[question.id] === alternative.id} onChange={() => mutate((current) => ({ ...current, simulationAttempts: current.simulationAttempts.map((item) => item.id === currentAttempt.id ? { ...item, answers: { ...item.answers, [question.id]: alternative.id } } : item) }))} /><strong>{alternative.id}</strong><span>{alternative.text}</span></label>)}</article><div className="attempt-navigation"><button className="secondary-button" disabled={!questionIndex} onClick={() => setQuestionIndex((value) => value - 1)}><ChevronLeft /> Anterior</button>{questionIndex < currentAttempt.questions.length - 1 ? <button className="primary-button" onClick={() => setQuestionIndex((value) => value + 1)}>Próxima <ChevronRight /></button> : <button className="primary-button" onClick={() => submitAttempt(currentAttempt)}><CheckCircle2 /> Finalizar</button>}</div></section></main>; }

  return <main className={`${embedded ? "" : "page "}question-area`}><nav className="question-tabs"><button className={tab === "bank" ? "active" : ""} onClick={() => setTab("bank")}>Banco de questões</button><button className={tab === "simulations" ? "active" : ""} onClick={() => setTab("simulations")}>Simulados</button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}>Histórico</button></nav>
  {tab === "bank" && <><div className="section-heading"><div><span className="eyebrow">ACERVO PESSOAL</span><h2>{questions.length} questões encontradas</h2></div><div className="heading-actions"><button className="secondary-button" onClick={() => setImportOpen(!importOpen)}><FileInput /> Importar texto</button><button className="primary-button" onClick={() => { setEditing(undefined); setAlternatives(["", "", "", ""]); setFormOpen(!formOpen); }}><Plus /> Nova questão</button></div></div>
  {formOpen && <form className="panel question-form" onSubmit={saveQuestion}><label className="wide">Enunciado<textarea name="statement" defaultValue={editing?.statement} maxLength={LIMITS.questionStatement} required autoFocus /></label>{alternatives.map((value, index) => <label key={index}>Alternativa {String.fromCharCode(65 + index)}<input value={value} onChange={(event) => setAlternatives((items) => items.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} required={index < 2} /></label>)}<label>Gabarito<select name="answer" defaultValue={editing?.correctAlternativeId ?? "A"}>{alternatives.map((_, index) => <option key={index}>{String.fromCharCode(65 + index)}</option>)}</select></label>{!fixedSubjectId && <label>Matéria (opcional)<select name="subjectId" defaultValue={editing?.subjectId ?? ""}><option value="">Geral</option>{data.subjects.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label>}<label>Coleção<input name="collection" defaultValue={editing?.collection ?? "Geral"} /></label><label>Categorias<input name="categories" defaultValue={editing?.categories.join(", ")} placeholder="Sintaxe, ESA 2014" /></label><label>Instituição<input name="institution" defaultValue={editing?.institution} /></label><label>Ano<input name="year" type="number" min="1900" max="2200" defaultValue={editing?.year} /></label><label className="wide">Explicação do gabarito<textarea name="explanation" defaultValue={editing?.explanation} /></label><label className="wide">Fonte<input name="source" defaultValue={editing?.source} /></label><div className="form-actions wide"><button type="button" className="text-button" onClick={resetForm}>Cancelar</button><button className="primary-button">{editing ? "Salvar questão" : "Adicionar questão"}</button></div></form>}
  {importOpen && <section className="panel question-import"><div><h3>Importação em texto</h3><p>Use diretivas entre colchetes, alternativas de A) a H), <code>= B</code> para o gabarito e <code>---</code> entre questões.</p></div><textarea value={importText} onChange={(event) => { setImportText(event.target.value); setPreview(undefined); }} /><div className="import-actions"><button className="secondary-button" onClick={() => setImportOpen(false)}>Cancelar</button><button className="primary-button" onClick={() => setPreview(parseQuestionsText(importText, data.subjects, fixedSubjectId))}>Validar conteúdo</button></div>{preview && <div className={`import-result ${preview.errors.length ? "has-errors" : ""}`}><strong>{preview.questions.length} questões válidas</strong>{preview.errors.map((error) => <small key={error}>{error}</small>)}{preview.questions.slice(0, 3).map((question, index) => <article className="import-preview" key={index}><b>{index + 1}. {question.statement}</b><span>{question.collection} · {question.alternatives.length} alternativas</span></article>)}{preview.questions.length > 3 && <small>+ {preview.questions.length - 3} questões reconhecidas</small>}{!preview.errors.length && !!preview.questions.length && <button className="primary-button" onClick={importQuestions}>Confirmar importação</button>}</div>}</section>}
  <section className="question-filters"><label className="search-box"><Search /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar enunciado, coleção ou categoria" /></label>{!fixedSubjectId && <select value={subjectFilter} onChange={(event) => setSubjectFilter(event.target.value)}><option value="all">Todas as matérias</option><option value="">Geral</option>{data.subjects.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select>}<select value={collection} onChange={(event) => setCollection(event.target.value)}><option value="all">Todas as coleções</option>{collections.map((item) => <option key={item}>{item}</option>)}</select><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Todas as categorias</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></section>
  <section className="panel bulk-manager question-bulk"><div className="bulk-manager-head"><div><strong>Organização em massa</strong><small>{selected.size} questões selecionadas</small></div><button className="secondary-button" onClick={selectVisible}><CheckCircle2 /> Selecionar visíveis</button><select value={selectionCategory} onChange={(event) => setSelectionCategory(event.target.value)}><option value="">Selecionar por categoria</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><button className="secondary-button" disabled={!selectionCategory} onClick={selectCategoryItems}>Selecionar categoria</button><button className="text-button" onClick={() => setSelected(new Set())}>Limpar</button></div>{selected.size > 0 && <div className="bulk-edit-row"><button className="secondary-button" onClick={editSelectedCollection}><Pencil /> Editar coleção</button><button className="secondary-button" onClick={editSelectedCategories}><Pencil /> Editar categorias</button>{!fixedSubjectId && <><select value={bulkSubject} onChange={(event) => setBulkSubject(event.target.value)}><option value="">Mover para matéria...</option><option value="general">Geral</option>{data.subjects.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select><button className="secondary-button" disabled={!bulkSubject} onClick={moveSelectedSubject}>Mover</button></>}<button className="secondary-button danger-outline" onClick={deleteSelected}><Trash2 /> Excluir selecionadas</button></div>}</section>
  <div className="question-list">{questions.map((question) => <article className="panel question-card" key={question.id}><button className={`question-select ${selected.has(question.id) ? "active" : ""}`} onClick={() => setSelected((value) => { const next = new Set(value); next.has(question.id) ? next.delete(question.id) : next.add(question.id); return next; })} aria-label="Selecionar questão">{selected.has(question.id) && <CheckCircle2 />}</button><div><span>{question.collection} · {subjectName(data, question.subjectId)}</span><h3>{question.statement}</h3><small>{question.categories.join(" · ") || "Sem categoria"}{question.year ? ` · ${question.year}` : ""}</small></div><div className="question-actions"><button onClick={() => editQuestion(question)}><Pencil /></button><button className="danger" onClick={() => removeQuestion(question.id)}><Trash2 /></button></div></article>)}{!questions.length && <div className="panel empty-state empty-wide"><CircleHelp /><h3>Nenhuma questão encontrada</h3><p>Cadastre manualmente ou importe um bloco de texto.</p></div>}</div></>}
  {tab === "simulations" && <><form className="panel simulation-builder" onSubmit={createSimulation}><div><span className="eyebrow">NOVO MODELO</span><h2>Monte um simulado</h2><p>{selected.size ? `${selected.size} questões selecionadas no banco` : `${questions.length} questões dos filtros atuais`}</p></div><label>Título<input name="title" required placeholder="Ex.: Simulado ESA 2014" /></label><label>Nota mínima (0–10)<input name="passingScore" type="number" min="0" max="10" step="0.1" defaultValue="5" /></label><label className="check-label"><input name="shuffleQuestions" type="checkbox" defaultChecked /><Shuffle /> Embaralhar questões</label><label className="check-label"><input name="shuffleAlternatives" type="checkbox" defaultChecked /><Shuffle /> Embaralhar alternativas</label><button className="primary-button" disabled={!selected.size && !questions.length}>Salvar modelo</button></form><div className="simulation-list">{visibleSimulations.map((simulation) => { const ongoing = data.simulationAttempts.find((item) => item.simulationId === simulation.id && item.status === "in_progress"); return <article className="panel simulation-card" key={simulation.id}><div><span className="eyebrow">MODELO SALVO</span><h3>{simulation.title}</h3><p>{simulation.questionIds.length} questões · meta {simulation.passingScore.toLocaleString("pt-BR")}</p></div><div>{ongoing && <button className="secondary-button" onClick={() => { setActiveAttempt(ongoing.id); setQuestionIndex(0); }}>Continuar</button>}<button className="primary-button" onClick={() => startSimulation(simulation.id)}><Play /> {ongoing ? "Nova tentativa" : "Iniciar"}</button><button className="icon-button danger" onClick={() => window.confirm(`Excluir o modelo “${simulation.title}”?`) && mutate((current) => ({ ...current, simulations: current.simulations.filter((item) => item.id !== simulation.id) }))}><Trash2 /></button></div></article>; })}{!visibleSimulations.length && <div className="panel empty-state"><Play /><h3>Nenhum modelo salvo</h3><p>Selecione questões no banco ou use os filtros atuais para montar o primeiro.</p></div>}</div></>}
  {tab === "history" && <div className="attempt-history">{attempts.map((attempt) => { const tone = resultTone(attempt); return <article className="history-entry" key={attempt.id}><div className="panel history-card"><span className={`history-status ${tone}`}>{tone === "failed" ? <XCircle /> : tone === "pending" ? <Play /> : <CheckCircle2 />}</span><div><h3>{attempt.title}</h3><p>{attempt.status === "completed" ? `${attempt.score?.toLocaleString("pt-BR")} de 10 · ${tone === "failed" ? "Abaixo da meta" : tone === "near" ? "Na faixa da meta" : "Meta atingida"}` : `${Object.keys(attempt.answers).length} de ${attempt.questions.length} respondidas`}</p><small>Iniciado em {new Date(attempt.startedAt).toLocaleString("pt-BR")}</small></div>{attempt.status === "in_progress" ? <button className="primary-button" onClick={() => { setActiveAttempt(attempt.id); setQuestionIndex(0); }}>Continuar</button> : <button className="secondary-button" onClick={() => setReviewing(reviewing === attempt.id ? undefined : attempt.id)}>{reviewing === attempt.id ? "Fechar revisão" : "Revisar gabarito"}</button>}<button className="icon-button danger" onClick={() => window.confirm("Excluir esta tentativa do histórico?") && mutate((current) => ({ ...current, simulationAttempts: current.simulationAttempts.filter((item) => item.id !== attempt.id) }))}><Trash2 /></button></div>{reviewing === attempt.id && attempt.status === "completed" && <div className="panel attempt-review">{attempt.questions.map((question, index) => { const answer = attempt.answers[question.id]; const correct = answer === question.correctAlternativeId; return <article key={question.id}><span>Questão {index + 1} · {correct ? "Acertou" : answer ? "Errou" : "Não respondida"}</span><h4>{question.statement}</h4>{question.alternatives.map((alternative) => <p className={`${alternative.id === question.correctAlternativeId ? "correct" : ""} ${alternative.id === answer && !correct ? "wrong" : ""}`} key={alternative.id}><b>{alternative.id}</b>{alternative.text}{alternative.id === question.correctAlternativeId && <small>Gabarito</small>}{alternative.id === answer && <small>Sua resposta</small>}</p>)}{question.explanation && <aside><strong>Comentário</strong>{question.explanation}</aside>}</article>; })}</div>}</article>; })}{!attempts.length && <div className="panel empty-state"><CircleHelp /><h3>Nenhuma tentativa</h3><p>Seus simulados iniciados e concluídos aparecerão aqui.</p></div>}</div>}</main>;
}
export default Questoes;
