import { ArrowLeft, BookOpen, BriefcaseBusiness, CheckCircle2, CheckSquare2, ChevronRight, FileText, NotebookPen, Pencil, Plus, Timer as TimerIcon, Trash2 } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import TimerPanel from "../components/TimerPanel";
import { LIMITS, formatTimer, type AppData, type Assignment, type Note, type TimerState } from "../data";
import Checklists from "./Checklists";
import Flashcards from "./Flashcards";

type Tab = "overview" | "assignments" | "checklists" | "timer" | "notebooks" | "flashcards";
type Props = { data: AppData; subjectId: string; onBack: () => void; mutate: (updater: (data: AppData) => AppData) => void; onTimerStart: (timer: TimerState) => void; onTimerUpdate: (timer: TimerState) => void; onTimerDelete: (id: string) => void; onTimerComplete: (timer: TimerState, seconds: number) => void };

function NoteEditor({ note, onSave, onDelete }: { note: Note; onSave: (note: Note) => void; onDelete: () => void }) {
  const [title, setTitle] = useState(note.title); const [content, setContent] = useState(note.content); const saved = title === note.title && content === note.content;
  useEffect(() => { if (saved) return; const timeout = window.setTimeout(() => onSave({ ...note, title: title.trim() || "Sem título", content, updatedAt: new Date().toISOString() }), 700); return () => clearTimeout(timeout); }, [title, content, note, onSave, saved]);
  return <div className="note-editor"><div className="note-editor-head"><input value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)} aria-label="Título da anotação" /><span>{saved ? "Salvo" : "Salvando..."}</span><button className="icon-button danger" onClick={onDelete} aria-label="Excluir anotação"><Trash2 size={17} /></button></div><textarea value={content} maxLength={LIMITS.noteContent} onChange={(event) => setContent(event.target.value)} placeholder="Comece a escrever sua anotação..." aria-label="Conteúdo da anotação" /><small>{content.length.toLocaleString("pt-BR")} de {LIMITS.noteContent.toLocaleString("pt-BR")} caracteres</small></div>;
}

function SubjectWorkspace({ data, subjectId, onBack, mutate, onTimerStart, onTimerUpdate, onTimerDelete, onTimerComplete }: Props) {
  const [tab, setTab] = useState<Tab>("overview"); const [showForm, setShowForm] = useState(false); const [openNotebook, setOpenNotebook] = useState<string>(); const [openNote, setOpenNote] = useState<string>();
  const subject = data.subjects.find((item) => item.id === subjectId); if (!subject) return null;
  const assignments = data.assignments.filter((item) => item.subjectId === subjectId); const checklists = data.checklists.filter((item) => item.subjectId === subjectId);
  const cards = data.flashcards.filter((item) => item.subjectId === subjectId); const notebooks = data.notebooks.filter((item) => item.subjectId === subjectId); const notes = data.notes.filter((item) => item.subjectId === subjectId); const timer = data.timers.find((item) => item.subjectId === subjectId);
  const submitAssignment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (assignments.length >= LIMITS.assignmentsPerSubject || data.assignments.length >= LIMITS.assignments) return; const form = new FormData(event.currentTarget); mutate((current) => ({ ...current, assignments: [{ id: crypto.randomUUID(), subjectId, title: String(form.get("title")).trim(), description: String(form.get("description")).trim(), dueDate: String(form.get("dueDate")), priority: String(form.get("priority")) as Assignment["priority"], completed: false }, ...current.assignments] })); setShowForm(false); };
  const createNotebook = () => { const title = window.prompt("Nome do novo caderno:")?.trim(); if (!title || notebooks.length >= LIMITS.notebooksPerSubject || data.notebooks.length >= LIMITS.notebooks) return; const id = crypto.randomUUID(); const createdAt = new Date().toISOString(); mutate((current) => ({ ...current, notebooks: [...current.notebooks, { id, subjectId, title: title.slice(0, 120), createdAt, updatedAt: createdAt }] })); setOpenNotebook(id); setOpenNote(undefined); };
  const renameNotebook = (id: string) => { const notebook = notebooks.find((item) => item.id === id); if (!notebook) return; const title = window.prompt("Novo nome do caderno:", notebook.title)?.trim(); if (title) mutate((current) => ({ ...current, notebooks: current.notebooks.map((item) => item.id === id ? { ...item, title: title.slice(0, 120), updatedAt: new Date().toISOString() } : item) })); };
  const deleteNotebook = (id: string) => { const notebook = notebooks.find((item) => item.id === id); if (!notebook || !window.confirm(`Excluir “${notebook.title}” e todas as suas anotações?`)) return; mutate((current) => ({ ...current, notebooks: current.notebooks.filter((item) => item.id !== id), notes: current.notes.filter((item) => item.notebookId !== id) })); if (openNotebook === id) { setOpenNotebook(undefined); setOpenNote(undefined); } };
  const createNote = (notebookId: string) => { const id = crypto.randomUUID(); const createdAt = new Date().toISOString(); mutate((current) => ({ ...current, notebooks: current.notebooks.map((item) => item.id === notebookId ? { ...item, updatedAt: createdAt } : item), notes: [...current.notes, { id, notebookId, subjectId, title: "Nova anotação", content: "", createdAt, updatedAt: createdAt }] })); setOpenNote(id); };
  const deleteNote = (id: string) => { const note = notes.find((item) => item.id === id); if (!note || !window.confirm(`Excluir a anotação “${note.title}”?`)) return; mutate((current) => ({ ...current, notes: current.notes.filter((item) => item.id !== id) })); const remaining = notes.find((item) => item.notebookId === note.notebookId && item.id !== id); setOpenNote(remaining?.id); };
  const nav = [{ id: "overview", label: "Visão geral" }, { id: "assignments", label: "Trabalhos" }, { id: "checklists", label: "Checklists" }, { id: "timer", label: "Timer" }, { id: "notebooks", label: "Cadernos" }, { id: "flashcards", label: "Flashcards" }] as const;
  const bannerSeconds = timer ? (timer.type === "pomodoro" ? timer.remainingSeconds : timer.elapsedSeconds) : 0;
  return <main className="subject-workspace" style={{ "--subject-color": subject.color } as React.CSSProperties}><header className="subject-header"><button className="back-button" onClick={onBack} aria-label="Voltar para matérias"><ArrowLeft /></button><span className="subject-dot" /><div><span className="eyebrow">ESPAÇO DA MATÉRIA</span><h1>{subject.title}</h1></div></header>{timer && tab !== "timer" && <button className="subject-timer-banner" onClick={() => setTab("timer")}><TimerIcon size={17} /><span><strong>{timer.type === "pomodoro" ? `${timer.mode === "focus" ? "Foco" : "Intervalo"} em ${subject.title}` : `Cronômetro de ${subject.title}`}</strong><small>{formatTimer(bannerSeconds, timer.type === "stopwatch")} · {timer.status === "running" ? "em andamento" : "pausado"}</small></span><ChevronRight /></button>}<nav className="subject-tabs">{nav.map((item) => <button className={tab === item.id ? "active" : ""} onClick={() => { setTab(item.id); setShowForm(false); }} key={item.id}>{item.label}</button>)}</nav>
  {tab === "overview" && <section className="subject-overview"><div className="subject-welcome"><span className="eyebrow">SUA ROTINA</span><h2>Tudo sobre {subject.title},<br />em um só lugar.</h2><p>Continue de onde parou ou organize o próximo passo.</p>{timer ? <button className="primary-button" onClick={() => setTab("timer")}><TimerIcon size={18} /> Continuar sessão</button> : <button className="primary-button" onClick={() => setTab("timer")}><TimerIcon size={18} /> Iniciar foco</button>}</div><div className="subject-overview-grid"><button onClick={() => setTab("assignments")}><BriefcaseBusiness /><strong>{assignments.filter((item) => !item.completed).length}</strong><span>trabalhos pendentes</span></button><button onClick={() => setTab("checklists")}><CheckSquare2 /><strong>{checklists.length}</strong><span>checklists</span></button><button onClick={() => setTab("notebooks")}><NotebookPen /><strong>{notebooks.length}</strong><span>cadernos</span></button><button onClick={() => setTab("flashcards")}><BookOpen /><strong>{cards.length}</strong><span>flashcards</span></button></div></section>}
  {tab === "assignments" && <section className="subject-section"><div className="section-heading"><div><span className="eyebrow">PROJETOS E ENTREGAS</span><h2>Seus trabalhos</h2></div><button className="primary-button" onClick={() => setShowForm(!showForm)}><Plus size={18} /> Novo trabalho</button></div>{showForm && <form className="subject-inline-form panel" onSubmit={submitAssignment}><label>Título<input name="title" maxLength={LIMITS.title} required autoFocus /></label><label>Descrição<input name="description" maxLength={10_000} /></label><label>Prazo<input name="dueDate" type="date" required /></label><label>Prioridade<select name="priority"><option>Média</option><option>Alta</option><option>Baixa</option></select></label><button className="primary-button">Adicionar</button></form>}<div className="panel subject-items">{assignments.map((item) => <div className={`assignment-row ${item.completed ? "completed" : ""}`} key={item.id}><button className="check-button" onClick={() => mutate((current) => ({ ...current, assignments: current.assignments.map((entry) => entry.id === item.id ? { ...entry, completed: !entry.completed } : entry) }))}>{item.completed && <CheckCircle2 size={14} />}</button><div><strong>{item.title}</strong><small>{item.description || "Sem descrição"}</small></div><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span><time>{new Date(`${item.dueDate}T12:00`).toLocaleDateString("pt-BR")}</time><button className="icon-button danger" onClick={() => window.confirm(`Excluir “${item.title}”?`) && mutate((current) => ({ ...current, assignments: current.assignments.filter((entry) => entry.id !== item.id) }))}><Trash2 size={17} /></button></div>)}{!assignments.length && <div className="empty-state"><BriefcaseBusiness /><p>Nenhum trabalho cadastrado.</p></div>}</div></section>}
  {tab === "checklists" && <section className="subject-section embedded-checklists"><Checklists data={data} mutate={mutate} fixedSubjectId={subjectId} /></section>}
  {tab === "timer" && <section className="subject-section timer-subject"><TimerPanel scope="subject" subjectId={subjectId} timer={timer} label={subject.title} onStart={onTimerStart} onUpdate={onTimerUpdate} onDelete={onTimerDelete} onComplete={onTimerComplete} /></section>}
  {tab === "notebooks" && <section className="subject-section"><div className="section-heading"><div><span className="eyebrow">ANOTAÇÕES</span><h2>Seus cadernos</h2></div><button className="primary-button" onClick={createNotebook}><Plus size={18} /> Novo caderno</button></div>{openNotebook ? <div className="notebook-workspace"><aside><button className="text-button" onClick={() => { setOpenNotebook(undefined); setOpenNote(undefined); }}><ArrowLeft size={16} /> Cadernos</button><div className="notebook-aside-title"><h3>{notebooks.find((item) => item.id === openNotebook)?.title}</h3><button onClick={() => renameNotebook(openNotebook)} aria-label="Renomear caderno"><Pencil size={14} /></button><button className="danger" onClick={() => deleteNotebook(openNotebook)} aria-label="Excluir caderno"><Trash2 size={14} /></button></div>{notes.filter((item) => item.notebookId === openNotebook).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).map((note) => <button className={openNote === note.id ? "active" : ""} onClick={() => setOpenNote(note.id)} key={note.id}><FileText size={15} /><span>{note.title}</span></button>)}<button className="new-note" onClick={() => createNote(openNotebook)}><Plus size={15} /> Nova anotação</button></aside><div>{openNote && notes.find((item) => item.id === openNote) ? <NoteEditor key={openNote} note={notes.find((item) => item.id === openNote)!} onSave={(note) => mutate((current) => ({ ...current, notebooks: current.notebooks.map((item) => item.id === note.notebookId ? { ...item, updatedAt: note.updatedAt } : item), notes: current.notes.map((item) => item.id === note.id ? note : item) }))} onDelete={() => deleteNote(openNote)} /> : <div className="empty-state"><NotebookPen /><p>Selecione ou crie uma anotação.</p></div>}</div></div> : <div className="notebook-grid">{notebooks.map((notebook) => <article className="notebook-card" key={notebook.id}><button className="notebook-card-main" onClick={() => { setOpenNotebook(notebook.id); setOpenNote(notes.filter((item) => item.notebookId === notebook.id).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0]?.id); }}><NotebookPen /><div><strong>{notebook.title}</strong><small>{notes.filter((item) => item.notebookId === notebook.id).length} anotações · atualizado em {new Date(notebook.updatedAt).toLocaleDateString("pt-BR")}</small></div><ChevronRight /></button><div className="notebook-card-actions"><button onClick={() => renameNotebook(notebook.id)} aria-label="Renomear"><Pencil /></button><button className="danger" onClick={() => deleteNotebook(notebook.id)} aria-label="Excluir"><Trash2 /></button></div></article>)}{!notebooks.length && <div className="empty-state panel empty-wide"><NotebookPen /><h3>Nenhum caderno</h3><p>Crie um caderno para começar suas anotações.</p></div>}</div>}</section>}
  {tab === "flashcards" && <section className="subject-section embedded-cards"><Flashcards cards={cards} subjects={data.subjects} fixedSubject={subject} onAdd={(card) => mutate((current) => ({ ...current, flashcards: [...current.flashcards, { ...card, id: crypto.randomUUID(), mastered: false }] }))} onToggleMastered={(id) => mutate((current) => ({ ...current, flashcards: current.flashcards.map((item) => item.id === id ? { ...item, mastered: !item.mastered } : item) }))} onRemove={(id) => mutate((current) => ({ ...current, flashcards: current.flashcards.filter((item) => item.id !== id) }))} /></section>}</main>;
}
export default SubjectWorkspace;
