import { BookOpen, Grid2X2, List, MoreVertical, Plus, Timer, Trash2 } from "lucide-react";
import { useState, type FormEvent } from "react";
import { LIMITS, SUBJECT_COLORS, formatTimer, type AppData, type Subject } from "../data";
type Props = { data: AppData; onOpen: (id: string) => void; onAdd: (subject: Omit<Subject, "id" | "createdAt">) => void; onRemove: (id: string, action: "delete" | "general") => void; onViewChange: (view: "grid" | "list") => void };
function Subjects({ data, onOpen, onAdd, onRemove, onViewChange }: Props) {
  const [showForm, setShowForm] = useState(false); const [color, setColor] = useState(SUBJECT_COLORS[0]); const [deleting, setDeleting] = useState<Subject>();
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (data.subjects.length >= LIMITS.subjects) return; const form = new FormData(event.currentTarget); onAdd({ title: String(form.get("title")).trim(), color }); event.currentTarget.reset(); setShowForm(false); };
  const remove = (action: "delete" | "general") => { if (!deleting) return; onRemove(deleting.id, action); setDeleting(undefined); };
  return <main className="page subjects-page"><div className="page-toolbar"><p className="muted">{data.subjects.length} de {LIMITS.subjects} matérias</p><div className="subject-toolbar"><div className="view-switch"><button className={data.subjectView === "grid" ? "active" : ""} onClick={() => onViewChange("grid")}><Grid2X2 /></button><button className={data.subjectView === "list" ? "active" : ""} onClick={() => onViewChange("list")}><List /></button></div><button className="primary-button" onClick={() => setShowForm(!showForm)}><Plus /> Nova matéria</button></div></div>
  {showForm && <form className="subject-create panel" onSubmit={submit}><label>Nome da matéria<input name="title" maxLength={LIMITS.subjectTitle} autoFocus required /></label><fieldset><legend>Cor de identificação</legend><div className="color-picker">{SUBJECT_COLORS.map((item) => <button type="button" aria-label={`Cor ${item}`} className={color === item ? "selected" : ""} style={{ background: item }} onClick={() => setColor(item)} key={item} />)}</div></fieldset><button className="primary-button">Criar matéria</button></form>}
  <section className={`subject-collection ${data.subjectView}`}>{data.subjects.map((subject) => { const checklists = data.checklists.filter((item) => item.subjectId === subject.id).length; const assignments = data.assignments.filter((item) => item.subjectId === subject.id && !item.completed).length; const cards = data.flashcards.filter((item) => item.subjectId === subject.id).length; const timer = data.timers.find((item) => item.subjectId === subject.id); return <article className="subject-card" style={{ "--subject-color": subject.color } as React.CSSProperties} key={subject.id}><button className="subject-card-main" onClick={() => onOpen(subject.id)}><span className="subject-dot" /><div className="subject-card-copy"><h3 title={subject.title}>{subject.title}</h3><p>{assignments} trabalhos · {checklists} checklists</p><div className="subject-card-meta"><span><BookOpen /> {cards} cartões</span>{timer && <span className="saved-timer"><Timer /> {timer.type === "pomodoro" ? "Pomodoro" : formatTimer(timer.elapsedSeconds, true)}</span>}</div></div></button><details className="card-menu"><summary><MoreVertical /></summary><button onClick={() => setDeleting(subject)}><Trash2 /> Excluir matéria</button></details></article>; })}{!data.subjects.length && <div className="empty-state panel empty-wide"><BookOpen /><h3>Seu espaço começa com uma matéria</h3><p>Reúna trabalhos, checklists, cadernos, timers, materiais, questões e flashcards.</p><button className="primary-button" onClick={() => setShowForm(true)}><Plus /> Criar primeira matéria</button></div>}</section>
  {deleting && <div className="modal-backdrop"><section className="modal subject-delete-modal"><span className="eyebrow">EXCLUIR MATÉRIA</span><h2>O que fazer com as questões?</h2><p>Os demais conteúdos de <strong>{deleting.title}</strong> serão excluídos. Tentativas concluídas permanecem preservadas.</p><div className="delete-choice"><button className="secondary-button" onClick={() => remove("general")}><BookOpen /> Migrar para Geral<small>Move para a coleção “Questões migradas”.</small></button><button className="secondary-button danger-outline" onClick={() => remove("delete")}><Trash2 /> Excluir questões<small>Remove do banco e atualiza os modelos.</small></button></div><button className="text-button" onClick={() => setDeleting(undefined)}>Cancelar</button></section></div>}</main>;
}
export default Subjects;
