import { ChevronDown, ChevronLeft, ChevronRight, EyeOff, GripHorizontal, Maximize2, Minimize2, Pause, PinOff, Play, RefreshCw } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import MarkdownView from "./MarkdownView";
import { toggleMarkdownCheckbox } from "../markdownUtils";
import type { AppData, NoteWidgetState } from "../data";

type Props = { data: AppData; mutate: (updater: (data: AppData) => AppData) => void; onOpen: () => void; allowDock?: boolean };
type Point = { x: number; y: number };
const dimensions = (size: NoteWidgetState["size"]) => size === "compact" ? { width: 270, height: 190 } : size === "expanded" ? { width: 480, height: 570 } : { width: 350, height: 390 };
const clampPoint = (point: Point, size: NoteWidgetState["size"]) => { const box = dimensions(size); return { x: Math.max(6, Math.min(window.innerWidth - Math.min(box.width, window.innerWidth - 12) - 6, point.x)), y: Math.max(6, Math.min(window.innerHeight - Math.min(box.height, window.innerHeight - 12) - 6, point.y)) }; };
const dockPoint = (point: Point, size: NoteWidgetState["size"]) => { const box = dimensions(size); const width = Math.min(box.width, window.innerWidth - 12); const height = Math.min(box.height, window.innerHeight - 12); const threshold = 74; let { x, y } = clampPoint(point, size); if (x < threshold) x = 6; else if (window.innerWidth - (x + width) < threshold) x = window.innerWidth - width - 6; if (y < threshold) y = 6; else if (window.innerHeight - (y + height) < threshold) y = window.innerHeight - height - 6; return { x, y }; };
const overlaps = (a: DOMRect | { left: number; top: number; right: number; bottom: number }, b: DOMRect) => a.left < b.right && a.right > b.left && a.top < b.bottom && a.bottom > b.top;

function FloatingNote({ data, mutate, onOpen, allowDock = false }: Props) {
  const widget = data.noteWidget; const [position, setPosition] = useState<Point>({ x: widget.x, y: widget.y }); const [selecting, setSelecting] = useState(false); const [pushing, setPushing] = useState(false); const [dragging, setDragging] = useState(false); const [hovering, setHovering] = useState(false);
  const drag = useRef<{ dx: number; dy: number; lastX: number; lastY: number } | undefined>(undefined); const positionRef = useRef(position); const pushTimer = useRef<number | undefined>(undefined);
  useEffect(() => { positionRef.current = position; }, [position]);
  useEffect(() => { if (!drag.current) setPosition(clampPoint({ x: widget.x, y: widget.y }, widget.size)); }, [widget.x, widget.y, widget.size]);
  useEffect(() => { if (hovering || data.noteSlideshow.status !== "running" || data.noteSlideshow.noteIds.length === 0) return; const timeout = window.setTimeout(() => mutate((current) => { const ids = current.noteSlideshow.noteIds.filter((id) => current.quickNotes.some((note) => note.id === id)); if (!ids.length) return { ...current, noteSlideshow: { ...current.noteSlideshow, status: "paused", enabled: false } }; const atEnd = current.noteSlideshow.currentIndex >= ids.length - 1; if (atEnd && !current.noteSlideshow.repeat) return { ...current, noteSlideshow: { ...current.noteSlideshow, status: "paused", currentIndex: ids.length - 1 } }; let nextIndex = atEnd ? 0 : current.noteSlideshow.currentIndex + 1; if (current.noteSlideshow.shuffle && ids.length > 1) { do nextIndex = Math.floor(Math.random() * ids.length); while (nextIndex === current.noteSlideshow.currentIndex); } const noteId = ids[nextIndex]; return { ...current, noteSlideshow: { ...current.noteSlideshow, noteIds: ids, currentIndex: nextIndex, lastChangedAt: Date.now() }, noteWorkspace: { ...current.noteWorkspace, activeNoteId: noteId }, noteWidget: current.noteWidget.visible && !current.noteWidget.detachedFromActiveNote ? { ...current.noteWidget, noteId } : current.noteWidget }; }), data.noteSlideshow.intervalSeconds * 1000); return () => window.clearTimeout(timeout); }, [hovering, data.noteSlideshow.status, data.noteSlideshow.currentIndex, data.noteSlideshow.intervalSeconds, data.noteSlideshow.noteIds, data.noteSlideshow.repeat, data.noteSlideshow.shuffle, mutate]);
  useEffect(() => { const pushed = (event: Event) => { const detail = (event as CustomEvent<Point>).detail; const next = clampPoint(detail, widget.size); setPushing(true); setPosition(next); window.clearTimeout(pushTimer.current); pushTimer.current = window.setTimeout(() => { setPushing(false); mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, ...next } })); }, 170); }; window.addEventListener("omnidesk-push-note", pushed); return () => { window.removeEventListener("omnidesk-push-note", pushed); window.clearTimeout(pushTimer.current); }; }, [mutate, widget.size]);
  useEffect(() => { if (!widget.visible || !widget.noteId) return; const timeout = window.setTimeout(() => { const own = document.getElementById("floating-note")?.getBoundingClientRect(); const timer = document.querySelector<HTMLElement>(".timer-widget,.timer-widget-restore")?.getBoundingClientRect(); if (!own || !timer || !overlaps(own, timer)) return; const preferredY = timer.bottom + 14 + own.height <= window.innerHeight ? timer.bottom + 14 : timer.top - own.height - 14; const next = clampPoint({ x: own.left, y: preferredY }, widget.size); setPosition(next); mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, ...next } })); }, 40); return () => window.clearTimeout(timeout); }, [widget.visible, widget.noteId, widget.size, mutate]);
  const note = data.quickNotes.find((item) => item.id === widget.noteId); const available = useMemo(() => data.quickNotes.filter((item) => !item.archived), [data.quickNotes]);
  if (!widget.visible || !note) return null;
  const box = dimensions(widget.size); const width = Math.min(box.width, window.innerWidth - 12); const height = Math.min(box.height, window.innerHeight - 84); const rightGap = window.innerWidth - (position.x + width); const bottomGap = window.innerHeight - (position.y + height); const dock = position.x <= 7 ? "left" : rightGap <= 7 ? "right" : position.y <= 73 ? "top" : bottomGap <= 7 ? "bottom" : "free";
  const begin = (event: React.PointerEvent) => { const wasDocked = widget.mode === "docked"; const start = wasDocked ? clampPoint({ x: event.clientX - Math.min(width / 2, 80), y: event.clientY - 24 }, widget.size) : position; if (wasDocked) { setPosition(start); mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, mode: "floating", ...start } })); } drag.current = { dx: event.clientX - start.x, dy: event.clientY - start.y, lastX: event.clientX, lastY: event.clientY }; setDragging(true); event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: React.PointerEvent) => { if (!drag.current) return; const delta = { x: event.clientX - drag.current.lastX, y: event.clientY - drag.current.lastY }; drag.current.lastX = event.clientX; drag.current.lastY = event.clientY; const next = clampPoint({ x: event.clientX - drag.current.dx, y: event.clientY - drag.current.dy }, widget.size); setPosition(next); document.getElementById("app")?.classList.toggle("note-dock-preview", allowDock && event.clientX < 380 && window.innerWidth >= 980); const timer = document.querySelector<HTMLElement>(".timer-widget,.timer-widget-restore"); if (timer) { const timerRect = timer.getBoundingClientRect(); const noteRect = { left: next.x, top: next.y, right: next.x + width, bottom: next.y + height }; if (overlaps(noteRect, timerRect)) { const verticalPush = Math.abs(delta.y) > 1 ? delta.y * 4 : (next.y + height / 2 < timerRect.top + timerRect.height / 2 ? 110 : -110); window.dispatchEvent(new CustomEvent("omnidesk-push-timer", { detail: { x: delta.x < 0 ? 0 : delta.x > 0 ? window.innerWidth : timerRect.left, y: timerRect.top + verticalPush } })); } } };
  const release = (event: React.PointerEvent) => { if (!drag.current) return; event.currentTarget.releasePointerCapture(event.pointerId); drag.current = undefined; setDragging(false); const shouldDock = allowDock && event.clientX < 380 && window.innerWidth >= 980; document.getElementById("app")?.classList.remove("note-dock-preview"); if (shouldDock) { mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, mode: "docked", size: "normal" } })); return; } const next = dockPoint(positionRef.current, widget.size); setPosition(next); mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, mode: "floating", ...next } })); };
  const updateContent = (content: string) => mutate((current) => ({ ...current, quickNotes: current.quickNotes.map((item) => item.id === note.id ? { ...item, content, updatedAt: new Date().toISOString() } : item) }));
  const stepSlide = (direction: -1 | 1) => mutate((current) => { const ids = current.noteSlideshow.noteIds.filter((id) => current.quickNotes.some((item) => item.id === id && !item.archived)); if (!ids.length) return current; const currentIndex = Math.max(0, ids.indexOf(current.noteWidget.noteId ?? "")); const nextIndex = (currentIndex + direction + ids.length) % ids.length; const noteId = ids[nextIndex]; return { ...current, noteSlideshow: { ...current.noteSlideshow, noteIds: ids, currentIndex: nextIndex, lastChangedAt: Date.now() }, noteWorkspace: { ...current.noteWorkspace, activeNoteId: noteId }, noteWidget: { ...current.noteWidget, noteId, detachedFromActiveNote: false } }; });
  const setSize = () => { const size = widget.size === "compact" ? "normal" : widget.size === "normal" ? "expanded" : "compact"; const next = clampPoint(position, size); setPosition(next); mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, size, ...next } })); };
  const docked = widget.mode === "docked" && allowDock;
  return <aside id="floating-note" className={`floating-note ${widget.size} ${docked ? "note-panel-docked" : `dock-${dock}`} ${pushing ? "is-pushed" : ""} ${dragging ? "is-dragging" : ""}`} style={docked ? ({ "--note-color": note.color } as React.CSSProperties) : ({ left: position.x, top: position.y, width, height, "--note-color": note.color } as React.CSSProperties)} onMouseEnter={() => setHovering(true)} onMouseLeave={() => setHovering(false)}>
    <header className="floating-note-handle" onPointerDown={begin} onPointerMove={move} onPointerUp={release} onPointerCancel={release}><GripHorizontal /><span className="note-color-dot" /><strong>{note.title}</strong><small>{data.noteSlideshow.status === "running" ? `${data.noteSlideshow.currentIndex + 1}/${data.noteSlideshow.noteIds.length}` : "FIXADA"}</small></header>
    <div className="floating-note-tools"><button title="Escolher outra anotação" onClick={() => setSelecting(!selecting)}><ChevronDown /></button>{widget.detachedFromActiveNote && <button title="Sincronizar com a anotação aberta" onClick={() => mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, noteId: current.noteWorkspace.activeNoteId, detachedFromActiveNote: false } }))}><RefreshCw /></button>}<button title="Nota anterior" disabled={data.noteSlideshow.noteIds.length < 2} onClick={() => stepSlide(-1)}><ChevronLeft /></button><button title="Próxima nota" disabled={data.noteSlideshow.noteIds.length < 2} onClick={() => stepSlide(1)}><ChevronRight /></button><button title={data.noteSlideshow.status === "running" ? "Pausar slides" : "Continuar slides"} disabled={!data.noteSlideshow.enabled || !data.noteSlideshow.noteIds.length} onClick={() => mutate((current) => ({ ...current, noteSlideshow: { ...current.noteSlideshow, status: current.noteSlideshow.status === "running" ? "paused" : "running", lastChangedAt: Date.now() } }))}>{data.noteSlideshow.status === "running" ? <Pause /> : <Play />}</button><button title="Alterar tamanho" onClick={setSize}>{widget.size === "expanded" ? <Minimize2 /> : <Maximize2 />}</button><button title="Abrir em Anotações" onClick={onOpen}><PinOff /></button><button title="Ocultar" onClick={() => mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, visible: false } }))}><EyeOff /></button></div>
    {selecting && <div className="floating-note-picker">{available.map((item) => <button className={item.id === note.id ? "active" : ""} onClick={() => { mutate((current) => ({ ...current, noteWidget: { ...current.noteWidget, noteId: item.id, detachedFromActiveNote: item.id !== current.noteWorkspace.activeNoteId } })); setSelecting(false); }} key={item.id}><span style={{ background: item.color }} />{item.title}</button>)}</div>}
    <div className="floating-note-content"><MarkdownView compact={widget.size === "compact"} content={note.content} onToggleCheckbox={(index) => updateContent(toggleMarkdownCheckbox(note.content, index))} /></div>
  </aside>;
}
export default FloatingNote;
