import { forwardRef, useEffect, useImperativeHandle, useRef } from "react";
import "mathlive/fonts.css";
import "mathlive/static.css";

const escapeHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const inlineHtml = (value: string) => { const output: string[] = []; const pattern = /(\[\[math:([\s\S]*?)\]\]|\*\*(.+?)\*\*|\*(.+?)\*|~~(.+?)~~|~(.+?)~)/g; let cursor = 0; let match: RegExpExecArray | null; while ((match = pattern.exec(value))) { if (match.index > cursor) output.push(escapeHtml(value.slice(cursor, match.index))); if (match[2] !== undefined) output.push(`<span class="notebook-formula inline" contenteditable="false" data-latex="${escapeHtml(match[2])}">${escapeHtml(match[2])}</span>`); else if (match[3] !== undefined || match[4] !== undefined) output.push(`<strong>${escapeHtml(match[3] ?? match[4])}</strong>`); else output.push(`<del>${escapeHtml(match[5] ?? match[6])}</del>`); cursor = match.index + match[0].length; } if (cursor < value.length) output.push(escapeHtml(value.slice(cursor))); return output.join(""); };
const contentHtml = (content: string) => { if (!content) return ""; const lines = content.split("\n"); const output: string[] = []; let index = 0; while (index < lines.length) { const line = lines[index]; const formula = line.trim().match(/^\[\[math:([\s\S]*?)\]\]$/); if (formula) { output.push(`<div class="notebook-formula block" contenteditable="false" data-latex="${escapeHtml(formula[1])}" data-block="true">${escapeHtml(formula[1])}</div>`); index += 1; continue; } const ordered = /^\s*\d+\.\s+/.test(line); const unordered = /^\s*-\s+/.test(line); if (ordered || unordered) { const tag = ordered ? "ol" : "ul"; const expression = ordered ? /^\s*\d+\.\s+(.*)$/ : /^\s*-\s+(.*)$/; const items: string[] = []; while (index < lines.length) { const item = lines[index].match(expression); if (!item) break; items.push(`<li>${inlineHtml(item[1])}</li>`); index += 1; } output.push(`<${tag}>${items.join("")}</${tag}>`); continue; } output.push(line ? `<div>${inlineHtml(line)}</div>` : "<div><br></div>"); index += 1; } return output.join(""); };
const serializeChildren = (node: Node): string => Array.from(node.childNodes).map(serializeNode).join("");
const serializeNode = (node: Node): string => { if (node.nodeType === Node.TEXT_NODE) return node.textContent ?? ""; if (!(node instanceof HTMLElement)) return ""; const latex = node.dataset.latex; if (latex !== undefined) return node.dataset.block === "true" ? `\n[[math:${latex}]]\n` : `[[math:${latex}]]`; const tag = node.tagName.toLowerCase(); if (tag === "br") return "\n"; if (tag === "strong" || tag === "b") return `*${serializeChildren(node)}*`; if (tag === "del" || tag === "s" || tag === "strike") return `~${serializeChildren(node)}~`; if (tag === "ul" || tag === "ol") return Array.from(node.children).map((item, index) => `${tag === "ol" ? `${index + 1}.` : "-"} ${serializeChildren(item).replace(/\n+/g, " ").trim()}`).join("\n") + "\n"; if (tag === "div" || tag === "p") return `${serializeChildren(node)}\n`; return serializeChildren(node); };

export type NotebookEditorHandle = { format: (command: "bold" | "strikeThrough" | "insertUnorderedList" | "insertOrderedList") => void; rememberSelection: () => void; insertFormula: (latex: string, block: boolean) => void; focus: () => void };

const NotebookEditor = forwardRef<NotebookEditorHandle, { content: string; onChange: (content: string) => void }>(function NotebookEditor({ content, onChange }, forwardedRef) {
  const editor = useRef<HTMLDivElement>(null); const lastEmitted = useRef(content); const selection = useRef<Range | undefined>(undefined);
  const emit = () => { if (!editor.current) return; const value = serializeChildren(editor.current).replace(/\n{3,}/g, "\n\n").replace(/\n$/, ""); lastEmitted.current = value; onChange(value); };
  const renderMath = async () => { const formulas = editor.current?.querySelectorAll<HTMLElement>("[data-latex]"); if (!formulas?.length) return; const { convertLatexToMarkup } = await import("mathlive"); formulas.forEach((formula) => { if (formula.dataset.latex) formula.innerHTML = convertLatexToMarkup(formula.dataset.latex); }); };
  useEffect(() => { if (!editor.current || content === lastEmitted.current && editor.current.innerHTML) return; editor.current.innerHTML = contentHtml(content); lastEmitted.current = content; void renderMath(); }, [content]);
  const rememberSelection = () => { const current = window.getSelection(); if (current?.rangeCount && editor.current?.contains(current.anchorNode)) selection.current = current.getRangeAt(0).cloneRange(); };
  const restoreSelection = () => { if (!selection.current) return; const current = window.getSelection(); current?.removeAllRanges(); current?.addRange(selection.current); };
  useImperativeHandle(forwardedRef, () => ({ focus: () => editor.current?.focus(), rememberSelection, format: (command) => { editor.current?.focus(); restoreSelection(); document.execCommand(command); rememberSelection(); emit(); }, insertFormula: (latex, block) => { editor.current?.focus(); restoreSelection(); const element = document.createElement("span"); element.className = `notebook-formula ${block ? "block" : "inline"}`; element.contentEditable = "false"; element.dataset.latex = latex; if (block) element.dataset.block = "true"; element.textContent = latex; const range = window.getSelection()?.rangeCount ? window.getSelection()!.getRangeAt(0) : undefined; if (range && editor.current?.contains(range.commonAncestorContainer)) { range.deleteContents(); range.insertNode(element); range.setStartAfter(element); range.collapse(true); const current = window.getSelection(); current?.removeAllRanges(); current?.addRange(range); } else editor.current?.append(element); emit(); void renderMath(); } }));
  const pastePlain = (event: React.ClipboardEvent<HTMLDivElement>) => { event.preventDefault(); document.execCommand("insertText", false, event.clipboardData.getData("text/plain")); emit(); };
  return <div ref={editor} className="notebook-live-editor" contentEditable suppressContentEditableWarning spellCheck onInput={emit} onKeyUp={rememberSelection} onMouseUp={rememberSelection} onFocus={rememberSelection} onPaste={pastePlain} data-placeholder="Comece a escrever. Use a barra para formatar ou inserir fórmulas." />;
});

export default NotebookEditor;
