import { ArrowRight, BookOpenCheck, Download, ShieldCheck } from "lucide-react";
import { useRef, useState, type FormEvent } from "react";
import type { AppData, Profile } from "../data";
import { readBackup } from "../storage";

type Props = { error: string; onComplete: (profile: Profile) => void; onImport: (data: AppData) => void };
function Onboarding({ error, onComplete, onImport }: Props) {
  const fileInput = useRef<HTMLInputElement>(null); const [importError, setImportError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); onComplete({ name: String(form.get("name")).trim(), course: String(form.get("course")).trim(), objective: String(form.get("objective")).trim(), weeklyGoal: Number(form.get("weeklyGoal")) }); };
  const importFile = async (file?: File) => { if (!file) return; try { onImport(await readBackup(file)); } catch (reason) { setImportError(reason instanceof Error ? reason.message : "Não foi possível importar o backup."); } };
  return <main className="onboarding"><section className="onboarding-intro"><div className="onboarding-brand"><BookOpenCheck /> <strong><span>Omni</span>Desk</strong></div><div className="onboarding-message"><span className="eyebrow">SEU ESPAÇO DE ESTUDOS</span><h1>Organize menos. Aprenda mais.</h1><p>Prazos, foco, anotações e revisões reunidos em uma rotina simples que funciona até sem internet.</p></div><div className="privacy-note"><ShieldCheck /><span><strong>Seus dados são seus.</strong> Tudo fica salvo somente neste dispositivo. Você pode criar um backup quando quiser.</span></div></section><section className="onboarding-form-area"><form onSubmit={submit}><span className="eyebrow">PRIMEIRO ACESSO</span><h2>Vamos preparar seu espaço</h2><p>Leva menos de um minuto. Você poderá alterar tudo depois.</p>{(error || importError) && <div className="form-error">{error || importError}</div>}<label>Como podemos chamar você?<input name="name" autoFocus maxLength={60} placeholder="Seu nome" required /></label><label>Curso ou área de estudo<input name="course" maxLength={80} placeholder="Ex.: Engenharia de Software" required /></label><label>Objetivo atual <span className="optional">opcional</span><input name="objective" maxLength={160} placeholder="Ex.: concluir a graduação ou passar em um concurso" /></label><label>Meta semanal de estudo<span className="field-help">Quanto tempo você pretende estudar por semana?</span><span className="input-with-unit"><input name="weeklyGoal" type="number" min="1" max="80" defaultValue="5" required /><strong>horas</strong></span></label><button className="primary-button onboarding-submit">Começar agora <ArrowRight size={18} /></button><div className="onboarding-separator"><span>ou</span></div><input ref={fileInput} type="file" accept="application/json,.json" hidden onChange={(event) => importFile(event.target.files?.[0])} /><button className="import-button" type="button" onClick={() => fileInput.current?.click()}><Download size={18} /> Restaurar um backup</button></form></section></main>;
}
export default Onboarding;
