import { BookOpen, CheckSquare2, GraduationCap, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import { SUBJECT_COLORS, type Checklist, type Flashcard, type Subject } from "../data";
type Props = { subjects: Subject[]; onClose: () => void; onAddChecklist: (checklist: Pick<Checklist, "title" | "description" | "subjectId">) => void; onAddCard: (card: Omit<Flashcard, "id" | "mastered">) => void; onAddSubject: (subject: Omit<Subject, "id" | "createdAt">) => void };
function QuickActionModal({ subjects, onClose, onAddChecklist, onAddCard, onAddSubject }: Props) {
  const [type, setType] = useState<"checklist" | "card" | "subject">("checklist"); const [color, setColor] = useState(SUBJECT_COLORS[0]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const subjectId = String(form.get("subjectId") || "") || undefined; const subjectName = subjects.find((item) => item.id === subjectId)?.title ?? "Geral"; if (type === "checklist") onAddChecklist({ title: String(form.get("title")).trim(), description: String(form.get("description")).trim(), subjectId }); else if (type === "card") onAddCard({ question: String(form.get("question")).trim(), answer: String(form.get("answer")).trim(), subject: subjectName, subjectId, deck: String(form.get("deck")).trim() || "Geral" }); else onAddSubject({ title: String(form.get("title")).trim(), color }); onClose(); };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="quick-title"><div className="modal-header"><div><span className="eyebrow">AÇÃO RÁPIDA</span><h2 id="quick-title">Adicionar à sua rotina</h2></div><button className="icon-button" onClick={onClose} aria-label="Fechar"><X /></button></div><div className="action-tabs three"><button className={type === "checklist" ? "active" : ""} onClick={() => setType("checklist")}><CheckSquare2 /> Checklist</button><button className={type === "card" ? "active" : ""} onClick={() => setType("card")}><BookOpen /> Flashcard</button><button className={type === "subject" ? "active" : ""} onClick={() => setType("subject")}><GraduationCap /> Matéria</button></div><form className="modal-form" onSubmit={submit}>{type === "checklist" && <><label>Título<input name="title" maxLength={160} autoFocus required /></label><label>Descrição <span className="optional">opcional</span><input name="description" maxLength={500} /></label></>}{type === "card" && <><label>Pergunta<input name="question" maxLength={1000} autoFocus required /></label><label>Resposta<textarea name="answer" maxLength={5000} required /></label><label>Bloco<input name="deck" placeholder="Geral" maxLength={80} /></label></>}{type === "subject" ? <><label>Nome da matéria<input name="title" maxLength={80} autoFocus required /></label><fieldset className="modal-colors"><legend>Cor</legend>{SUBJECT_COLORS.map((item) => <button type="button" className={color === item ? "selected" : ""} style={{ background: item }} onClick={() => setColor(item)} key={item} />)}</fieldset></> : <label>Matéria<select name="subjectId"><option value="">Geral</option>{subjects.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label>}<button className="primary-button">Adicionar</button></form></section></div>;
}
export default QuickActionModal;
