import { BookOpen, CalendarPlus, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import type { Flashcard, Task } from "../data";
type Props = { onClose: () => void; onAddTask: (task: Omit<Task, "id" | "completed">) => void; onAddCard: (card: Omit<Flashcard, "id" | "mastered">) => void };
function QuickActionModal({ onClose, onAddTask, onAddCard }: Props) {
  const [type, setType] = useState<"task" | "card">("task"); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (type === "task") onAddTask({ title: String(form.get("title")), subject: String(form.get("subject")), dueDate: String(form.get("dueDate")), priority: String(form.get("priority")) as Task["priority"] }); else onAddCard({ question: String(form.get("question")), answer: String(form.get("answer")), subject: String(form.get("subject")) }); onClose(); };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="quick-title"><div className="modal-header"><div><span className="eyebrow">AÇÃO RÁPIDA</span><h2 id="quick-title">Adicionar à sua rotina</h2></div><button className="icon-button" onClick={onClose} aria-label="Fechar"><X /></button></div><div className="action-tabs"><button className={type === "task" ? "active" : ""} onClick={() => setType("task")}><CalendarPlus /> Prazo</button><button className={type === "card" ? "active" : ""} onClick={() => setType("card")}><BookOpen /> Flashcard</button></div><form className="modal-form" onSubmit={submit}>{type === "task" ? <><label>Tarefa<input name="title" autoFocus required /></label><label>Data<input type="date" name="dueDate" required /></label><label>Prioridade<select name="priority"><option>Média</option><option>Alta</option><option>Baixa</option></select></label></> : <><label>Pergunta<input name="question" autoFocus required /></label><label>Resposta<textarea name="answer" required /></label></>}<label>Matéria<input name="subject" required /></label><button className="primary-button">Adicionar</button></form></section></div>;
}
export default QuickActionModal;
